////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:4.0.30319.34014
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//using System.Xml.Serialization;

//namespace Business.XmlExportsData.Perfetto
//{
//    // 
//    // This source code was auto-generated by xsd, Version=4.0.30319.33440.
//    // 


//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.microarea.it/Schema/2004/Smart/ImpiantiNet/Rapportini/Rapportino/Users" +
//        "/sa/RapportiniSogedi.xsd")]
//    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.microarea.it/Schema/2004/Smart/ImpiantiNet/Rapportini/Rapportino/Users" +
//        "/sa/RapportiniSogedi.xsd", IsNullable = false)]
//    public partial class Rapportino
//    {

//        private Data dataField;

//        private Diagnostic diagnosticField;

//        private string tbNamespaceField;

//        private string xTechProfileField;

//        private bool postableField;

//        private bool postableFieldSpecified;

//        private bool postBackField;

//        private bool postBackFieldSpecified;

//        public Rapportino()
//        {
//            this.tbNamespaceField = "Document.ImpiantiNet.Rapportini.INRapportini.Rapportino";
//            this.xTechProfileField = "RapportiniSogedi";
//            this.postableField = true;
//            this.postBackField = true;
//        }

//        /// <remarks/>
//        public Data Data
//        {
//            get
//            {
//                return this.dataField;
//            }
//            set
//            {
//                this.dataField = value;
//            }
//        }

//        /// <remarks/>
//        public Diagnostic Diagnostic
//        {
//            get
//            {
//                return this.diagnosticField;
//            }
//            set
//            {
//                this.diagnosticField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string tbNamespace
//        {
//            get
//            {
//                return this.tbNamespaceField;
//            }
//            set
//            {
//                this.tbNamespaceField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string xTechProfile
//        {
//            get
//            {
//                return this.xTechProfileField;
//            }
//            set
//            {
//                this.xTechProfileField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public bool postable
//        {
//            get
//            {
//                return this.postableField;
//            }
//            set
//            {
//                this.postableField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool postableSpecified
//        {
//            get
//            {
//                return this.postableFieldSpecified;
//            }
//            set
//            {
//                this.postableFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public bool postBack
//        {
//            get
//            {
//                return this.postBackField;
//            }
//            set
//            {
//                this.postBackField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool postBackSpecified
//        {
//            get
//            {
//                return this.postBackFieldSpecified;
//            }
//            set
//            {
//                this.postBackFieldSpecified = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.microarea.it/Schema/2004/Smart/ImpiantiNet/Rapportini/Rapportino/Users" +
//        "/sa/RapportiniSogedi.xsd")]
//    public partial class Data
//    {

//        private DBTRapportiniTesta dBTRapportiniTestaField;

//        private DBTRapportiniRighe dBTRapportiniRigheField;

//        /// <remarks/>
//        public DBTRapportiniTesta DBTRapportiniTesta
//        {
//            get
//            {
//                return this.dBTRapportiniTestaField;
//            }
//            set
//            {
//                this.dBTRapportiniTestaField = value;
//            }
//        }

//        /// <remarks/>
//        public DBTRapportiniRighe DBTRapportiniRighe
//        {
//            get
//            {
//                return this.dBTRapportiniRigheField;
//            }
//            set
//            {
//                this.dBTRapportiniRigheField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.microarea.it/Schema/2004/Smart/ImpiantiNet/Rapportini/Rapportino/Users" +
//        "/sa/RapportiniSogedi.xsd")]
//    public partial class DBTRapportiniTesta
//    {

//        private DBTRapportiniTestaWorkingReportId workingReportIdField;

//        private System.DateTime workingReportDateField;

//        private bool workingReportDateFieldSpecified;

//        private string jobField;

//        private bool masterField;

//        private bool masterFieldSpecified;

//        public DBTRapportiniTesta()
//        {
//            this.masterField = true;
//        }

//        /// <remarks/>
//        public DBTRapportiniTestaWorkingReportId WorkingReportId
//        {
//            get
//            {
//                return this.workingReportIdField;
//            }
//            set
//            {
//                this.workingReportIdField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
//        public System.DateTime WorkingReportDate
//        {
//            get
//            {
//                return this.workingReportDateField;
//            }
//            set
//            {
//                this.workingReportDateField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool WorkingReportDateSpecified
//        {
//            get
//            {
//                return this.workingReportDateFieldSpecified;
//            }
//            set
//            {
//                this.workingReportDateFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        public string Job
//        {
//            get
//            {
//                return this.jobField;
//            }
//            set
//            {
//                this.jobField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public bool master
//        {
//            get
//            {
//                return this.masterField;
//            }
//            set
//            {
//                this.masterField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool masterSpecified
//        {
//            get
//            {
//                return this.masterFieldSpecified;
//            }
//            set
//            {
//                this.masterFieldSpecified = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.microarea.it/Schema/2004/Smart/ImpiantiNet/Rapportini/Rapportino/Users" +
//        "/sa/RapportiniSogedi.xsd")]
//    public partial class DBTRapportiniTestaWorkingReportId
//    {

//        private bool primaryKeyField;

//        private bool primaryKeyFieldSpecified;

//        private int valueField;

//        public DBTRapportiniTestaWorkingReportId()
//        {
//            this.primaryKeyField = true;
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public bool primaryKey
//        {
//            get
//            {
//                return this.primaryKeyField;
//            }
//            set
//            {
//                this.primaryKeyField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool primaryKeySpecified
//        {
//            get
//            {
//                return this.primaryKeyFieldSpecified;
//            }
//            set
//            {
//                this.primaryKeyFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlTextAttribute()]
//        public int Value
//        {
//            get
//            {
//                return this.valueField;
//            }
//            set
//            {
//                this.valueField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.microarea.it/Schema/2004/Smart/ImpiantiNet/Rapportini/Rapportino/Users" +
//        "/sa/RapportiniSogedi.xsd")]
//    public partial class Diagnostic
//    {

//        private DiagnosticError[] errorsField;

//        private DiagnosticWarning[] warningsField;

//        /// <remarks/>
//        [System.Xml.Serialization.XmlArrayItemAttribute("Error", IsNullable = false)]
//        public DiagnosticError[] Errors
//        {
//            get
//            {
//                return this.errorsField;
//            }
//            set
//            {
//                this.errorsField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlArrayItemAttribute("Warning", IsNullable = false)]
//        public DiagnosticWarning[] Warnings
//        {
//            get
//            {
//                return this.warningsField;
//            }
//            set
//            {
//                this.warningsField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.microarea.it/Schema/2004/Smart/ImpiantiNet/Rapportini/Rapportino/Users" +
//        "/sa/RapportiniSogedi.xsd")]
//    public partial class DiagnosticError
//    {

//        private int codeField;

//        private bool codeFieldSpecified;

//        private string sourceField;

//        private string messageField;

//        /// <remarks/>
//        public int Code
//        {
//            get
//            {
//                return this.codeField;
//            }
//            set
//            {
//                this.codeField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool CodeSpecified
//        {
//            get
//            {
//                return this.codeFieldSpecified;
//            }
//            set
//            {
//                this.codeFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        public string Source
//        {
//            get
//            {
//                return this.sourceField;
//            }
//            set
//            {
//                this.sourceField = value;
//            }
//        }

//        /// <remarks/>
//        public string Message
//        {
//            get
//            {
//                return this.messageField;
//            }
//            set
//            {
//                this.messageField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.microarea.it/Schema/2004/Smart/ImpiantiNet/Rapportini/Rapportino/Users" +
//        "/sa/RapportiniSogedi.xsd")]
//    public partial class DiagnosticWarning
//    {

//        private int codeField;

//        private bool codeFieldSpecified;

//        private string sourceField;

//        private string messageField;

//        /// <remarks/>
//        public int Code
//        {
//            get
//            {
//                return this.codeField;
//            }
//            set
//            {
//                this.codeField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool CodeSpecified
//        {
//            get
//            {
//                return this.codeFieldSpecified;
//            }
//            set
//            {
//                this.codeFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        public string Source
//        {
//            get
//            {
//                return this.sourceField;
//            }
//            set
//            {
//                this.sourceField = value;
//            }
//        }

//        /// <remarks/>
//        public string Message
//        {
//            get
//            {
//                return this.messageField;
//            }
//            set
//            {
//                this.messageField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.microarea.it/Schema/2004/Smart/ImpiantiNet/Rapportini/Rapportino/Users" +
//        "/sa/RapportiniSogedi.xsd")]
//    public partial class DBTRapportiniRigheRow
//    {

//        private DBTRapportiniRigheRowWorkingReportId workingReportIdField;

//        private DBTRapportiniRigheRowLine lineField;

//        private string employeeField;

//        private int ordinaryHoursField;

//        private bool ordinaryHoursFieldSpecified;

//        private int overtimeHoursField;

//        private bool overtimeHoursFieldSpecified;

//        private int travelHoursField;

//        private bool travelHoursFieldSpecified;

//        private string jobField;

//        private System.DateTime workingReportDateField;

//        private bool workingReportDateFieldSpecified;

//        private int customHours1Field;

//        private bool customHours1FieldSpecified;

//        private int customHours2Field;

//        private bool customHours2FieldSpecified;

//        private int customHours3Field;

//        private bool customHours3FieldSpecified;

//        private int customHours4Field;

//        private bool customHours4FieldSpecified;

//        private string noteField;

//        private int startHourField;

//        private bool startHourFieldSpecified;

//        private int endHourField;

//        private bool endHourFieldSpecified;

//        /// <remarks/>
//        public DBTRapportiniRigheRowWorkingReportId WorkingReportId
//        {
//            get
//            {
//                return this.workingReportIdField;
//            }
//            set
//            {
//                this.workingReportIdField = value;
//            }
//        }

//        /// <remarks/>
//        public DBTRapportiniRigheRowLine Line
//        {
//            get
//            {
//                return this.lineField;
//            }
//            set
//            {
//                this.lineField = value;
//            }
//        }

//        /// <remarks/>
//        public string Employee
//        {
//            get
//            {
//                return this.employeeField;
//            }
//            set
//            {
//                this.employeeField = value;
//            }
//        }

//        /// <remarks/>
//        public int OrdinaryHours
//        {
//            get
//            {
//                return this.ordinaryHoursField;
//            }
//            set
//            {
//                this.ordinaryHoursField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool OrdinaryHoursSpecified
//        {
//            get
//            {
//                return this.ordinaryHoursFieldSpecified;
//            }
//            set
//            {
//                this.ordinaryHoursFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        public int OvertimeHours
//        {
//            get
//            {
//                return this.overtimeHoursField;
//            }
//            set
//            {
//                this.overtimeHoursField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool OvertimeHoursSpecified
//        {
//            get
//            {
//                return this.overtimeHoursFieldSpecified;
//            }
//            set
//            {
//                this.overtimeHoursFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        public int TravelHours
//        {
//            get
//            {
//                return this.travelHoursField;
//            }
//            set
//            {
//                this.travelHoursField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool TravelHoursSpecified
//        {
//            get
//            {
//                return this.travelHoursFieldSpecified;
//            }
//            set
//            {
//                this.travelHoursFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        public string Job
//        {
//            get
//            {
//                return this.jobField;
//            }
//            set
//            {
//                this.jobField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
//        public System.DateTime WorkingReportDate
//        {
//            get
//            {
//                return this.workingReportDateField;
//            }
//            set
//            {
//                this.workingReportDateField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool WorkingReportDateSpecified
//        {
//            get
//            {
//                return this.workingReportDateFieldSpecified;
//            }
//            set
//            {
//                this.workingReportDateFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        public int CustomHours1
//        {
//            get
//            {
//                return this.customHours1Field;
//            }
//            set
//            {
//                this.customHours1Field = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool CustomHours1Specified
//        {
//            get
//            {
//                return this.customHours1FieldSpecified;
//            }
//            set
//            {
//                this.customHours1FieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        public int CustomHours2
//        {
//            get
//            {
//                return this.customHours2Field;
//            }
//            set
//            {
//                this.customHours2Field = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool CustomHours2Specified
//        {
//            get
//            {
//                return this.customHours2FieldSpecified;
//            }
//            set
//            {
//                this.customHours2FieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        public int CustomHours3
//        {
//            get
//            {
//                return this.customHours3Field;
//            }
//            set
//            {
//                this.customHours3Field = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool CustomHours3Specified
//        {
//            get
//            {
//                return this.customHours3FieldSpecified;
//            }
//            set
//            {
//                this.customHours3FieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        public int CustomHours4
//        {
//            get
//            {
//                return this.customHours4Field;
//            }
//            set
//            {
//                this.customHours4Field = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool CustomHours4Specified
//        {
//            get
//            {
//                return this.customHours4FieldSpecified;
//            }
//            set
//            {
//                this.customHours4FieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        public string Note
//        {
//            get
//            {
//                return this.noteField;
//            }
//            set
//            {
//                this.noteField = value;
//            }
//        }

//        /// <remarks/>
//        public int StartHour
//        {
//            get
//            {
//                return this.startHourField;
//            }
//            set
//            {
//                this.startHourField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool StartHourSpecified
//        {
//            get
//            {
//                return this.startHourFieldSpecified;
//            }
//            set
//            {
//                this.startHourFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        public int EndHour
//        {
//            get
//            {
//                return this.endHourField;
//            }
//            set
//            {
//                this.endHourField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool EndHourSpecified
//        {
//            get
//            {
//                return this.endHourFieldSpecified;
//            }
//            set
//            {
//                this.endHourFieldSpecified = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.microarea.it/Schema/2004/Smart/ImpiantiNet/Rapportini/Rapportino/Users" +
//        "/sa/RapportiniSogedi.xsd")]
//    public partial class DBTRapportiniRigheRowWorkingReportId
//    {

//        private bool primaryKeyField;

//        private bool primaryKeyFieldSpecified;

//        private int valueField;

//        public DBTRapportiniRigheRowWorkingReportId()
//        {
//            this.primaryKeyField = true;
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public bool primaryKey
//        {
//            get
//            {
//                return this.primaryKeyField;
//            }
//            set
//            {
//                this.primaryKeyField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool primaryKeySpecified
//        {
//            get
//            {
//                return this.primaryKeyFieldSpecified;
//            }
//            set
//            {
//                this.primaryKeyFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlTextAttribute()]
//        public int Value
//        {
//            get
//            {
//                return this.valueField;
//            }
//            set
//            {
//                this.valueField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.microarea.it/Schema/2004/Smart/ImpiantiNet/Rapportini/Rapportino/Users" +
//        "/sa/RapportiniSogedi.xsd")]
//    public partial class DBTRapportiniRigheRowLine
//    {

//        private bool primaryKeyField;

//        private bool primaryKeyFieldSpecified;

//        private short valueField;

//        public DBTRapportiniRigheRowLine()
//        {
//            this.primaryKeyField = true;
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public bool primaryKey
//        {
//            get
//            {
//                return this.primaryKeyField;
//            }
//            set
//            {
//                this.primaryKeyField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool primaryKeySpecified
//        {
//            get
//            {
//                return this.primaryKeyFieldSpecified;
//            }
//            set
//            {
//                this.primaryKeyFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlTextAttribute()]
//        public short Value
//        {
//            get
//            {
//                return this.valueField;
//            }
//            set
//            {
//                this.valueField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.microarea.it/Schema/2004/Smart/ImpiantiNet/Rapportini/Rapportino/Users" +
//        "/sa/RapportiniSogedi.xsd")]
//    public partial class DBTRapportiniRighe
//    {

//        private DBTRapportiniRigheRow[] dBTRapportiniRigheRowField;

//        private string updateTypeField;

//        public DBTRapportiniRighe()
//        {
//            this.updateTypeField = "0";
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute("DBTRapportiniRigheRow")]
//        public DBTRapportiniRigheRow[] DBTRapportiniRigheRow
//        {
//            get
//            {
//                return this.dBTRapportiniRigheRowField;
//            }
//            set
//            {
//                this.dBTRapportiniRigheRowField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
//        public string updateType
//        {
//            get
//            {
//                return this.updateTypeField;
//            }
//            set
//            {
//                this.updateTypeField = value;
//            }
//        }
//    }
//}