//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("it-IT")]
        public string CultureInfo {
            get {
                return ((string)(this["CultureInfo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Admin_Level {
            get {
                return ((int)(this["Admin_Level"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~\\FilesInput\\")]
        public string Files_Input_Path {
            get {
                return ((string)(this["Files_Input_Path"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~\\FilesOutput--CSV_TIMBRATURE\\")]
        public string Files_Output_Csv_Path
        {
            get
            {
                return ((string)(this["Files_Output_Csv_Path"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int GiorniDemo {
            get {
                return ((int)(this["GiorniDemo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int GiorniAvvisoScadenza {
            get {
                return ((int)(this["GiorniAvvisoScadenza"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~\\Menu\\menu.js")]
        public string PKPath {
            get {
                return ((string)(this["PKPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mypass")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~\\Menu\\menu2.js")]
        public string LastConn {
            get {
                return ((string)(this["LastConn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reg_Sospese")]
        public string SuspendedRegsFile {
            get {
                return ((string)(this["SuspendedRegsFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reg_DaImportare_BCK_{0}.txt")]
        public string RegsBCKFile {
            get {
                return ((string)(this["RegsBCKFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsSaveChangesLogActive {
            get {
                return ((bool)(this["IsSaveChangesLogActive"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~\\ExcelModels\\")]
        public string ExcelModelsPath {
            get {
                return ((string)(this["ExcelModelsPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsCheckFailedLogActive {
            get {
                return ((bool)(this["IsCheckFailedLogActive"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dd/MM/yyyy HH:mm")]
        public string DateTimeDisplayFormatString {
            get {
                return ((string)(this["DateTimeDisplayFormatString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MM/dd/yyyy HH:mm")]
        public string DateTimeDisplayFormatString_en_US {
            get {
                return ((string)(this["DateTimeDisplayFormatString_en_US"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PrintRecordAccessInErrorImport {
            get {
                return ((bool)(this["PrintRecordAccessInErrorImport"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int Winit_Level {
            get {
                return ((int)(this["Winit_Level"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~\\FilesInput\\Backup\\")]
        public string Files_Input_Backup_Path {
            get {
                return ((string)(this["Files_Input_Backup_Path"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reg_DaImportare")]
        public string RegFile {
            get {
                return ((string)(this["RegFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XmlConfig\\Colors.xml")]
        public string XmlColorConfigRelativeFilePath {
            get {
                return ((string)(this["XmlColorConfigRelativeFilePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XmlConfig\\Customization.xml")]
        public string XmlCustomizationConfigFileRelativePath {
            get {
                return ((string)(this["XmlCustomizationConfigFileRelativePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FilesOutput\\")]
        public string Files_Output_Path {
            get {
                return ((string)(this["Files_Output_Path"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~\\DeployVersion.txt")]
        public string Deploy_Version_File_Path {
            get {
                return ((string)(this["Deploy_Version_File_Path"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OPZIONI_REPORT")]
        public string OpzReportTableName {
            get {
                return ((string)(this["OpzReportTableName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ExportedToPerfetto.xml")]
        public string ExportedToPerfettoDatesColFile {
            get {
                return ((string)(this["ExportedToPerfettoDatesColFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("APIUSER")]
        public string APIUserName {
            get {
                return ((string)(this["APIUserName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~\\XmlConfig\\Modules.xml")]
        public string ModulesActivationFilePath {
            get {
                return ((string)(this["ModulesActivationFilePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Exports.ExportExcelCustom.ExportSpecialized.ExportConfrontoOreBudget")]
        public string BudgetConfrontationSpecialized {
            get {
                return ((string)(this["BudgetConfrontationSpecialized"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int MaxNonGpsRegLinePatternLength {
            get {
                return ((int)(this["MaxNonGpsRegLinePatternLength"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GPS")]
        public string GpsCantCodePrefix {
            get {
                return ((string)(this["GpsCantCodePrefix"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000")]
        public string GpsCantNumberStringFormat {
            get {
                return ((string)(this["GpsCantNumberStringFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ActivityAutoClosure")]
        public string ActivityAutoClosureCustomData {
            get {
                return ((string)(this["ActivityAutoClosureCustomData"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ATTIVWXYZ9")]
        public string EndActivityCode {
            get {
                return ((string)(this["EndActivityCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MarkedForDeletion")]
        public string ActivityMarkedForDeletionCustomData {
            get {
                return ((string)(this["ActivityMarkedForDeletionCustomData"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~\\FilesInput\\SignalJsonBackup\\")]
        public string Files_Input_JSON_Segnal_Backup_Path {
            get {
                return ((string)(this["Files_Input_JSON_Segnal_Backup_Path"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~\\FilesInput\\Backup\\Segnalazioni\\")]
        public string Files_Input_Segn_Backup_Path {
            get {
                return ((string)(this["Files_Input_Segn_Backup_Path"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~\\FilesInput\\Backup\\JsonTimbrature\\")]
        public string Files_Input_JSON_Backup_Path {
            get {
                return ((string)(this["Files_Input_JSON_Backup_Path"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~\\FilesInputBackupJsonAudio\\")]
        public string Files_Input_JSON_Audio_Backup_Path {
            get {
                return ((string)(this["Files_Input_JSON_Audio_Backup_Path"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~\\FilesInputBackupJsonActivity\\")]
        public string Files_Input_JSON_Activity_Backup_Path {
            get {
                return ((string)(this["Files_Input_JSON_Activity_Backup_Path"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~\\FilesInputClockAppAudio\\")]
        public string Files_Input_Audio_Path {
            get {
                return ((string)(this["Files_Input_Audio_Path"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~\\FilesInput\\Backup\\Col\\")]
        public string Files_Input_Col_Backup_Path {
            get {
                return ((string)(this["Files_Input_Col_Backup_Path"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~\\FilesInput\\Backup\\Cant\\")]
        public string Files_Input_Cant_Backup_Path {
            get {
                return ((string)(this["Files_Input_Cant_Backup_Path"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~\\FilesInput\\UserFiles")]
        public string Files_Input_UserFiles {
            get {
                return ((string)(this["Files_Input_UserFiles"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~\\FilesInput\\Backup\\Segnalazioni")]
        public string SegnBackup {
            get {
                return ((string)(this["SegnBackup"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segn_Sospese")]
        public string SuspendedSegnFile {
            get {
                return ((string)(this["SuspendedSegnFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~\\XmlConfig\\ExternalOperationsConfig.xml")]
        public string ExternalImportConfig {
            get {
                return ((string)(this["ExternalImportConfig"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TmpJsonDownload-{0}-{1}-{2}-{3}-{4}-{5}.txt")]
        public string JsonBackupFileNamePattern {
            get {
                return ((string)(this["JsonBackupFileNamePattern"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~\\XmlConfig\\SuperUsers.xml")]
        public string SuperUsersFilePath {
            get {
                return ((string)(this["SuperUsersFilePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>ATTIV</string>\r\n</ArrayOfString>")]
        public string[] DeviceActivityBaseCodes {
            get {
                return ((string[])(this["DeviceActivityBaseCodes"]));
            }
        }
    }
}
