//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.LicenceServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScheduleData", Namespace="http://schemas.datacontract.org/2004/07/LicenceServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class ScheduleData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerPublicKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobParametersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OwnerUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OwnerUserLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ScheduleCreationDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ScheduleEditDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ScheduleEndDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScheduleExclusionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScheduleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScheduleParametersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ScheduleStartDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScheduleTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerPublicKey {
            get {
                return this.CustomerPublicKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerPublicKeyField, value) != true)) {
                    this.CustomerPublicKeyField = value;
                    this.RaisePropertyChanged("CustomerPublicKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobParameters {
            get {
                return this.JobParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.JobParametersField, value) != true)) {
                    this.JobParametersField = value;
                    this.RaisePropertyChanged("JobParameters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobType {
            get {
                return this.JobTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.JobTypeField, value) != true)) {
                    this.JobTypeField = value;
                    this.RaisePropertyChanged("JobType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OwnerUserId {
            get {
                return this.OwnerUserIdField;
            }
            set {
                if ((this.OwnerUserIdField.Equals(value) != true)) {
                    this.OwnerUserIdField = value;
                    this.RaisePropertyChanged("OwnerUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OwnerUserLevel {
            get {
                return this.OwnerUserLevelField;
            }
            set {
                if ((this.OwnerUserLevelField.Equals(value) != true)) {
                    this.OwnerUserLevelField = value;
                    this.RaisePropertyChanged("OwnerUserLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ScheduleCreationDateTime {
            get {
                return this.ScheduleCreationDateTimeField;
            }
            set {
                if ((this.ScheduleCreationDateTimeField.Equals(value) != true)) {
                    this.ScheduleCreationDateTimeField = value;
                    this.RaisePropertyChanged("ScheduleCreationDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ScheduleEditDateTime {
            get {
                return this.ScheduleEditDateTimeField;
            }
            set {
                if ((this.ScheduleEditDateTimeField.Equals(value) != true)) {
                    this.ScheduleEditDateTimeField = value;
                    this.RaisePropertyChanged("ScheduleEditDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ScheduleEndDateTime {
            get {
                return this.ScheduleEndDateTimeField;
            }
            set {
                if ((this.ScheduleEndDateTimeField.Equals(value) != true)) {
                    this.ScheduleEndDateTimeField = value;
                    this.RaisePropertyChanged("ScheduleEndDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ScheduleExclusions {
            get {
                return this.ScheduleExclusionsField;
            }
            set {
                if ((object.ReferenceEquals(this.ScheduleExclusionsField, value) != true)) {
                    this.ScheduleExclusionsField = value;
                    this.RaisePropertyChanged("ScheduleExclusions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ScheduleId {
            get {
                return this.ScheduleIdField;
            }
            set {
                if ((this.ScheduleIdField.Equals(value) != true)) {
                    this.ScheduleIdField = value;
                    this.RaisePropertyChanged("ScheduleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ScheduleParameters {
            get {
                return this.ScheduleParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ScheduleParametersField, value) != true)) {
                    this.ScheduleParametersField = value;
                    this.RaisePropertyChanged("ScheduleParameters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ScheduleStartDateTime {
            get {
                return this.ScheduleStartDateTimeField;
            }
            set {
                if ((this.ScheduleStartDateTimeField.Equals(value) != true)) {
                    this.ScheduleStartDateTimeField = value;
                    this.RaisePropertyChanged("ScheduleStartDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ScheduleType {
            get {
                return this.ScheduleTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ScheduleTypeField, value) != true)) {
                    this.ScheduleTypeField = value;
                    this.RaisePropertyChanged("ScheduleType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModulesActivation", Namespace="http://schemas.datacontract.org/2004/07/LicenceServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class ModulesActivation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.LicenceServiceReference.ModulesTypeEnum ModuleTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.LicenceServiceReference.ModulesTypeEnum ModuleType {
            get {
                return this.ModuleTypeField;
            }
            set {
                if ((this.ModuleTypeField.Equals(value) != true)) {
                    this.ModuleTypeField = value;
                    this.RaisePropertyChanged("ModuleType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModulesTypeEnum", Namespace="http://schemas.datacontract.org/2004/07/LicenceServiceLibrary")]
    public enum ModulesTypeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Times = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Timesheet = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AmmountMinutes = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rounding = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nocturne = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Trips = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Activities = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Scheduler = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Gps = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pass = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BudgetComparing = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WhereIsIt = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OvertimeAuth = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Notification = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Privacy = 14,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UploadData", Namespace="http://schemas.datacontract.org/2004/07/LicenceServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class UploadData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FileContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublicKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FileContent {
            get {
                return this.FileContentField;
            }
            set {
                if ((object.ReferenceEquals(this.FileContentField, value) != true)) {
                    this.FileContentField = value;
                    this.RaisePropertyChanged("FileContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PublicKey {
            get {
                return this.PublicKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PublicKeyField, value) != true)) {
                    this.PublicKeyField = value;
                    this.RaisePropertyChanged("PublicKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LicenceData", Namespace="http://schemas.datacontract.org/2004/07/LicenceServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class LicenceData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LicenceExpirationDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LicenceExpirationDate {
            get {
                return this.LicenceExpirationDateField;
            }
            set {
                if ((this.LicenceExpirationDateField.Equals(value) != true)) {
                    this.LicenceExpirationDateField = value;
                    this.RaisePropertyChanged("LicenceExpirationDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LicenceServiceReference.ILicenceService")]
    public interface ILicenceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILicenceService/GetActivation", ReplyAction="http://tempuri.org/ILicenceService/GetActivationResponse")]
        string GetActivation(string publicKey, string customerName, System.DateTime lastConnection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILicenceService/SetUpdateData", ReplyAction="http://tempuri.org/ILicenceService/SetUpdateDataResponse")]
        void SetUpdateData(string publicKey, string updatePath, string connectionString, string applicationUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILicenceService/UpdateExpirationDate", ReplyAction="http://tempuri.org/ILicenceService/UpdateExpirationDateResponse")]
        void UpdateExpirationDate(string publicKey, System.DateTime expirationDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILicenceService/AddNewScheduledOperation", ReplyAction="http://tempuri.org/ILicenceService/AddNewScheduledOperationResponse")]
        bool AddNewScheduledOperation(string customerPublicKey, string scheduleType, string jobType, string schedulerParameters, string schedulerExclusions, string jobParameters, System.DateTime startSchedulerDate, System.DateTime endSchedulerDate, int userId, int userLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILicenceService/GetScheduleDatas", ReplyAction="http://tempuri.org/ILicenceService/GetScheduleDatasResponse")]
        Business.LicenceServiceReference.ScheduleData[] GetScheduleDatas(string customerPublicKey, int userId, int userLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILicenceService/RemoveScheduleData", ReplyAction="http://tempuri.org/ILicenceService/RemoveScheduleDataResponse")]
        bool RemoveScheduleData(string customerPublicKey, int scheduleId, int userId, int userLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILicenceService/GetModulesActivation", ReplyAction="http://tempuri.org/ILicenceService/GetModulesActivationResponse")]
        Business.LicenceServiceReference.ModulesActivation[] GetModulesActivation(string publicKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILicenceService/UploadRegFiles", ReplyAction="http://tempuri.org/ILicenceService/UploadRegFilesResponse")]
        string UploadRegFiles(Business.LicenceServiceReference.UploadData uploadData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILicenceService/GetLicenceExpiredAndInExpiration", ReplyAction="http://tempuri.org/ILicenceService/GetLicenceExpiredAndInExpirationResponse")]
        Business.LicenceServiceReference.LicenceData[] GetLicenceExpiredAndInExpiration(int numberOfDays);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILicenceService/UpdateWinitUserPassword", ReplyAction="http://tempuri.org/ILicenceService/UpdateWinitUserPasswordResponse")]
        void UpdateWinitUserPassword(string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILicenceService/GetWinitUserPassword", ReplyAction="http://tempuri.org/ILicenceService/GetWinitUserPasswordResponse")]
        string GetWinitUserPassword(string customerPublicKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILicenceServiceChannel : Business.LicenceServiceReference.ILicenceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LicenceServiceClient : System.ServiceModel.ClientBase<Business.LicenceServiceReference.ILicenceService>, Business.LicenceServiceReference.ILicenceService {
        
        public LicenceServiceClient() {
        }
        
        public LicenceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LicenceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LicenceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LicenceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetActivation(string publicKey, string customerName, System.DateTime lastConnection) {
            return base.Channel.GetActivation(publicKey, customerName, lastConnection);
        }
        
        public void SetUpdateData(string publicKey, string updatePath, string connectionString, string applicationUrl) {
            base.Channel.SetUpdateData(publicKey, updatePath, connectionString, applicationUrl);
        }
        
        public void UpdateExpirationDate(string publicKey, System.DateTime expirationDate) {
            base.Channel.UpdateExpirationDate(publicKey, expirationDate);
        }
        
        public bool AddNewScheduledOperation(string customerPublicKey, string scheduleType, string jobType, string schedulerParameters, string schedulerExclusions, string jobParameters, System.DateTime startSchedulerDate, System.DateTime endSchedulerDate, int userId, int userLevel) {
            return base.Channel.AddNewScheduledOperation(customerPublicKey, scheduleType, jobType, schedulerParameters, schedulerExclusions, jobParameters, startSchedulerDate, endSchedulerDate, userId, userLevel);
        }
        
        public Business.LicenceServiceReference.ScheduleData[] GetScheduleDatas(string customerPublicKey, int userId, int userLevel) {
            return base.Channel.GetScheduleDatas(customerPublicKey, userId, userLevel);
        }
        
        public bool RemoveScheduleData(string customerPublicKey, int scheduleId, int userId, int userLevel) {
            return base.Channel.RemoveScheduleData(customerPublicKey, scheduleId, userId, userLevel);
        }
        
        public Business.LicenceServiceReference.ModulesActivation[] GetModulesActivation(string publicKey) {
            return base.Channel.GetModulesActivation(publicKey);
        }
        
        public string UploadRegFiles(Business.LicenceServiceReference.UploadData uploadData) {
            return base.Channel.UploadRegFiles(uploadData);
        }
        
        public Business.LicenceServiceReference.LicenceData[] GetLicenceExpiredAndInExpiration(int numberOfDays) {
            return base.Channel.GetLicenceExpiredAndInExpiration(numberOfDays);
        }
        
        public void UpdateWinitUserPassword(string newPassword) {
            base.Channel.UpdateWinitUserPassword(newPassword);
        }
        
        public string GetWinitUserPassword(string customerPublicKey) {
            return base.Channel.GetWinitUserPassword(customerPublicKey);
        }
    }
}
