//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aut_Str
    {
        public int Aut_Str_Id { get; set; }
        public int Aut_Str_Col_Id { get; set; }
        public Nullable<int> Aut_Str_Resp_Id { get; set; }
        public System.DateTime Aut_Str_Data_Inizio { get; set; }
        public System.DateTime Aut_Str_Data_Fine { get; set; }
        public int Aut_Str_Num_Ore { get; set; }
        public string Aut_Str_Note { get; set; }
    
        public virtual Col Col { get; set; }
        public virtual Resp Resp { get; set; }
    }
}
