//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cant_CentroDiCosto
    {
        public int Cant_CentroDiCosto_Id { get; set; }
        public int Cant_Id { get; set; }
        public int CentroDiCosto_Id { get; set; }
    
        public virtual CentroDiCosto CentroDiCosto { get; set; }
        public virtual Cant Cant { get; set; }
    }
}
