//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cant_Note
    {
        public int Cant_Note_Id { get; set; }
        public int Cant_Id { get; set; }
        public System.DateTime DataOraUltimaModifica_Can_Note { get; set; }
        public System.DateTime Data_Nota_Can_Note { get; set; }
        public System.DateTime Data_Registrazione_Can_Note { get; set; }
        public bool DisAbilitazione_Can_Note { get; set; }
        public int Utenti_Id { get; set; }
        public string Nota_Can_Note { get; set; }
        public string Tipo_Nota_Can_Note { get; set; }
    
        public virtual Utenti Utenti { get; set; }
        public virtual Cant Cant { get; set; }
    }
}
