//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cant
    {
        public Cant()
        {
            this.Cant_CentroDiCosto = new HashSet<Cant_CentroDiCosto>();
            this.Cant_Note = new HashSet<Cant_Note>();
            this.Cant_Var = new HashSet<Cant_Var>();
            this.Col_Cant_Orario = new HashSet<Col_Cant_Orario>();
            this.Damage = new HashSet<Damage>();
            this.Fru_Cant = new HashSet<Fru_Cant>();
            this.Reg = new HashSet<Reg>();
            this.Param = new HashSet<Param>();
        }
    
        public int Cant_Id { get; set; }
        public Nullable<short> Arrot_Durata_Can { get; set; }
        public Nullable<double> Canone_Mensile_Fascia1_Can { get; set; }
        public Nullable<double> Canone_Mensile_Fascia2_Can { get; set; }
        public string Cap_Can { get; set; }
        public string Cap_Nascita_Can { get; set; }
        public Nullable<int> Cli_Id { get; set; }
        public string Cod_Fisc_Can { get; set; }
        public string Codice_Cantiere { get; set; }
        public string Codice_Luogo_Nascita_Can { get; set; }
        public string Codice_Luogo_Residenza_Can { get; set; }
        public string Codice_Voucher_Can { get; set; }
        public string Cognome_Assistito_Can { get; set; }
        public Nullable<double> Contributo_Disabili_Fascia1_Can { get; set; }
        public Nullable<double> Contributo_Disabili_Fascia2_Can { get; set; }
        public Nullable<double> Costo_Mezzora_Prescuola_Can { get; set; }
        public Nullable<double> Costo_Orario_Can { get; set; }
        public Nullable<System.DateTime> Data_Isee_Can { get; set; }
        public Nullable<System.DateTime> Data_Nascita_Can { get; set; }
        public Nullable<System.DateTime> Data_Rapporto_Fine_1_Can { get; set; }
        public Nullable<System.DateTime> Data_Rapporto_Fine_2_Can { get; set; }
        public Nullable<System.DateTime> Data_Rapporto_Fine_3_Can { get; set; }
        public Nullable<System.DateTime> Data_Rapporto_Fine_4_Can { get; set; }
        public Nullable<System.DateTime> Data_Rapporto_Fine_5_Can { get; set; }
        public Nullable<System.DateTime> Data_Rapporto_Inizio_1_Can { get; set; }
        public Nullable<System.DateTime> Data_Rapporto_Inizio_2_Can { get; set; }
        public Nullable<System.DateTime> Data_Rapporto_Inizio_3_Can { get; set; }
        public Nullable<System.DateTime> Data_Rapporto_Inizio_4_Can { get; set; }
        public Nullable<System.DateTime> Data_Rapporto_Inizio_5_Can { get; set; }
        public System.DateTime Data_Registrazione_Can { get; set; }
        public System.DateTime DataOraUltimaModifica_Can { get; set; }
        public Nullable<System.DateTime> DataVarGps_Can { get; set; }
        public string Descrizione_Can { get; set; }
        public bool DisAbilitazione_Can { get; set; }
        public Nullable<System.TimeSpan> Durata_Max_Gruppo_Notte_Ril_Can { get; set; }
        public Nullable<System.TimeSpan> Durata_Max_Gruppo_Ril_Can { get; set; }
        public Nullable<System.TimeSpan> Durata_Max_Ril_Can { get; set; }
        public Nullable<System.TimeSpan> Durata_Min_Ril_Can { get; set; }
        public string Fax_1_Can { get; set; }
        public string Fax_1_Rif_Can { get; set; }
        public string Fax_2_Can { get; set; }
        public string Fax_2_Rif_Can { get; set; }
        public Nullable<int> Fil_Id { get; set; }
        public Nullable<byte> Flag_NON_Esportare_Can { get; set; }
        public int FlagGps_Can { get; set; }
        public string Gestione_Can { get; set; }
        public string Indirizzo_Can { get; set; }
        public double LatitudineGps_Can { get; set; }
        public Nullable<System.TimeSpan> Limite_Inizio_Notte_Can { get; set; }
        public string Livello_Assistito_Can { get; set; }
        public double LongitudineGps_Can { get; set; }
        public string Luogo_Can { get; set; }
        public string Luogo_Nascita_Can { get; set; }
        public bool Mensa_Can { get; set; }
        public int Metodo_Arrotondamento_Can { get; set; }
        public Nullable<short> Minuti_Tolleranza_Can { get; set; }
        public Nullable<short> Minuti_Tolleranza_F_Can { get; set; }
        public string Nazione_Can { get; set; }
        public string Nazione_Nascita_Can { get; set; }
        public string Nome_Assistito_Can { get; set; }
        public string Note_Can { get; set; }
        public string Nr_Isee_Can { get; set; }
        public Nullable<short> Numero_Bimbi_Fascia_Can { get; set; }
        public Nullable<short> Numero_GG_Lavorativi { get; set; }
        public Nullable<short> Numero_Utenti_Fascia1_Can { get; set; }
        public Nullable<short> Numero_Utenti_Fascia2_Can { get; set; }
        public Nullable<short> Numero_Utenti_PreScuola_Can { get; set; }
        public Nullable<short> Numero_Utenti_PostScuola_1Mezzora_Can { get; set; }
        public Nullable<short> Numero_Utenti_PostScuola_2Mezzora_Can { get; set; }
        public Nullable<decimal> Ore_Massime_Can { get; set; }
        public Nullable<float> Percentuale_Can { get; set; }
        public Nullable<float> Percentuale_Servizio_1_Can { get; set; }
        public Nullable<float> Percentuale_Servizio_2_Can { get; set; }
        public Nullable<float> Percentuale_Servizio_3_Can { get; set; }
        public Nullable<float> Percentuale_Servizio_4_Can { get; set; }
        public Nullable<float> Percentuale_Servizio_5_Can { get; set; }
        public string Provincia_Can { get; set; }
        public string Provincia_Nascita_Can { get; set; }
        public Nullable<short> RaggioGps_Can { get; set; }
        public string Raggruppamento1_Can { get; set; }
        public string Raggruppamento2_Can { get; set; }
        public string Residenza_Interno_Can { get; set; }
        public string Residenza_Localita_Can { get; set; }
        public string Sesso_Can { get; set; }
        public bool Singola_Reg { get; set; }
        public Nullable<short> Soglia_Arrot_Fig_Can { get; set; }
        public Nullable<short> Soglia_Arrot_Fig_F_Can { get; set; }
        public Nullable<short> Soglia_Durata_Can { get; set; }
        public string Telefono_1_Can { get; set; }
        public string Telefono_1_Rif_Can { get; set; }
        public string Telefono_2_Can { get; set; }
        public string Telefono_2_Rif_Can { get; set; }
        public string Telefono_3_Can { get; set; }
        public string Telefono_3_Rif_Can { get; set; }
        public string Telefono_4_Can { get; set; }
        public string Telefono_4_Rif_Can { get; set; }
        public int Tipo_Arrotondamento_Can { get; set; }
        public string Tipo_Calcolo_Viaggi_Can { get; set; }
        public string Tipo_Cantiere_Can { get; set; }
        public string Tipo_Interv_Can { get; set; }
        public string Tipo_Servizio_1_Can { get; set; }
        public string Tipo_Servizio_2_Can { get; set; }
        public string Tipo_Servizio_3_Can { get; set; }
        public string Tipo_Servizio_4_Can { get; set; }
        public string Tipo_Servizio_5_Can { get; set; }
        public string Tipologia_Can { get; set; }
        public int TipoNotturno_Can { get; set; }
        public Nullable<System.TimeSpan> Turno1_Can { get; set; }
        public Nullable<System.TimeSpan> Turno2_Can { get; set; }
        public Nullable<System.TimeSpan> Turno3_Can { get; set; }
        public Nullable<System.TimeSpan> Turno4_Can { get; set; }
        public Nullable<System.TimeSpan> Turno5_Can { get; set; }
        public Nullable<System.TimeSpan> Turno6_Can { get; set; }
        public Nullable<System.TimeSpan> Turno7_Can { get; set; }
        public Nullable<System.TimeSpan> Turno8_Can { get; set; }
        public Nullable<System.TimeSpan> Turno9_Can { get; set; }
        public Nullable<System.TimeSpan> Turno10_Can { get; set; }
        public string Zona_Can { get; set; }
        public string Domicilio_Cap_Can { get; set; }
        public string Domicilio_Indirizzo_Can { get; set; }
        public string Domicilio_Interno_Can { get; set; }
        public string Domicilio_Localita_Can { get; set; }
        public string Domicilio_Luogo_Can { get; set; }
        public string Domicilio_Provincia_Can { get; set; }
        public string Codice_Domicilio_Luogo_Can { get; set; }
        public Nullable<int> Tab_Orari_Tipo_Id { get; set; }
        public string Frazione_Can { get; set; }
        public Nullable<System.TimeSpan> Limite_Entrata_Mattina_Cant { get; set; }
        public Nullable<System.TimeSpan> Limite_Entrata_Pomeriggio_Cant { get; set; }
        public Nullable<System.TimeSpan> Tolleranza_Limite_Entrata_Pomeriggio_Cant { get; set; }
        public Nullable<System.TimeSpan> Tempo_Attivita_Can { get; set; }
        public string Codice_Commessa_Can { get; set; }
        public string Codice_Gestionale_Can { get; set; }
        public Nullable<System.TimeSpan> Durata_Notturno_Can { get; set; }
        public Nullable<int> Cant_Padre_Id { get; set; }
        public string Codice_in_clockApp { get; set; }
        public Nullable<System.TimeSpan> Limite_Uscita_Mattina_Cant { get; set; }
        public Nullable<System.TimeSpan> Limite_Uscita_Pomeriggio_Cant { get; set; }
        public Nullable<System.TimeSpan> Tolleranza_Limite_Uscita_Pomeriggio_Cant { get; set; }
        public Nullable<System.TimeSpan> Tolleranza_Limite_Uscita_Mattina_Cant { get; set; }
        public Nullable<int> IdTerminale { get; set; }
        public Nullable<System.TimeSpan> Tolleranza_Limite_Entrata_Cant { get; set; }
        public Nullable<double> Importo1 { get; set; }
        public Nullable<double> Importo2 { get; set; }
        public Nullable<double> Importo3 { get; set; }
        public Nullable<double> Importo4 { get; set; }
        public Nullable<double> Importo5 { get; set; }
        public Nullable<double> Importo6 { get; set; }
        public Nullable<double> Importo7 { get; set; }
        public Nullable<double> Importo8 { get; set; }
        public Nullable<double> Importo9 { get; set; }
        public Nullable<double> Importo10 { get; set; }
    
        public virtual ICollection<Cant_CentroDiCosto> Cant_CentroDiCosto { get; set; }
        public virtual Cli Cli { get; set; }
        public virtual Fil Fil { get; set; }
        public virtual ICollection<Cant_Note> Cant_Note { get; set; }
        public virtual Tab_Orari_Tipo Tab_Orari_Tipo { get; set; }
        public virtual ICollection<Cant_Var> Cant_Var { get; set; }
        public virtual ICollection<Col_Cant_Orario> Col_Cant_Orario { get; set; }
        public virtual ICollection<Damage> Damage { get; set; }
        public virtual ICollection<Fru_Cant> Fru_Cant { get; set; }
        public virtual ICollection<Reg> Reg { get; set; }
        public virtual ICollection<Param> Param { get; set; }
    }
}
