//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CentroDiCosto
    {
        public CentroDiCosto()
        {
            this.Reg = new HashSet<Reg>();
            this.Cant_CentroDiCosto = new HashSet<Cant_CentroDiCosto>();
        }
    
        public int CentroDiCosto_Id { get; set; }
        public string Codice { get; set; }
        public string Descrizione { get; set; }
        public System.DateTime Inizio { get; set; }
        public System.DateTime Fine { get; set; }
    
        public virtual ICollection<Reg> Reg { get; set; }
        public virtual ICollection<Cant_CentroDiCosto> Cant_CentroDiCosto { get; set; }
    }
}
