//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cli
    {
        public Cli()
        {
            this.Utenti = new HashSet<Utenti>();
            this.Cant = new HashSet<Cant>();
        }
    
        public int Cli_Id { get; set; }
        public string Banca_Descrizione_Cli { get; set; }
        public string Banca_Iban_Cli { get; set; }
        public string Codice_Cliente { get; set; }
        public string Codice_Ditta_Cli { get; set; }
        public string Codice_Fiscale_Cli { get; set; }
        public string Cognome_Cli { get; set; }
        public Nullable<System.DateTime> Data_Rapporto_Fine_Cli { get; set; }
        public Nullable<System.DateTime> Data_Rapporto_Inizio_Cli { get; set; }
        public System.DateTime Data_Registrazione_Cli { get; set; }
        public System.DateTime DataOraUltimaModifica_Cli { get; set; }
        public bool DisAbilitazione_Cli { get; set; }
        public string Domicilio_Cap_Cli { get; set; }
        public string Domicilio_Indirizzo_Cli { get; set; }
        public string Domicilio_Luogo_Cli { get; set; }
        public string Domicilio_Provincia_Cli { get; set; }
        public string Domicilio_Nazione_Cli { get; set; }
        public string Fax_1_Cli { get; set; }
        public string Fax_1_Rif_Cli { get; set; }
        public string Fax_2_Cli { get; set; }
        public string Fax_2_Rif_Cli { get; set; }
        public string Lingua_Cli { get; set; }
        public string Nome_Cli { get; set; }
        public string Note_Cli { get; set; }
        public Nullable<byte> Pagamento_1Mese_Escl_Cli { get; set; }
        public Nullable<byte> Pagamento_2Mese_Escl_Cli { get; set; }
        public string Pagamento_Codice_Cli { get; set; }
        public string Pagamento_GF_Cli { get; set; }
        public Nullable<byte> Pagamento_GG_Cli { get; set; }
        public Nullable<byte> Pagamento_Intervallo_Cli { get; set; }
        public Nullable<byte> Pagamento_Rate_Cli { get; set; }
        public Nullable<float> Pagamento_Sconto_Cli { get; set; }
        public string Partita_Iva_Cli { get; set; }
        public string Residenza_Cap_Cli { get; set; }
        public string Residenza_Indirizzo_Cli { get; set; }
        public string Residenza_Luogo_Cli { get; set; }
        public string Residenza_Nazione_Cli { get; set; }
        public string Residenza_Provincia_Cli { get; set; }
        public string Telefono_1_Cli { get; set; }
        public string Telefono_1_Rif_Cli { get; set; }
        public string Telefono_2_Cli { get; set; }
        public string Telefono_2_Rif_Cli { get; set; }
        public string Telefono_3_Cli { get; set; }
        public string Telefono_3_Rif_Cli { get; set; }
        public string Telefono_4_Cli { get; set; }
        public string Telefono_4_Rif_Cli { get; set; }
        public string Valuta_Cli { get; set; }
    
        public virtual ICollection<Utenti> Utenti { get; set; }
        public virtual ICollection<Cant> Cant { get; set; }
    }
}
