//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Col_Cant_Orario
    {
        public int Col_Cant_Orario_Id { get; set; }
        public Nullable<int> Col_Id { get; set; }
        public Nullable<int> Cant_Id { get; set; }
        public string Codice_Motivazione_Orario { get; set; }
        public short Anno_Orario { get; set; }
        public byte Mese_Orario { get; set; }
        public decimal Minuti_G1_Orario { get; set; }
        public decimal Minuti_G2_Orario { get; set; }
        public decimal Minuti_G3_Orario { get; set; }
        public decimal Minuti_G4_Orario { get; set; }
        public decimal Minuti_G5_Orario { get; set; }
        public decimal Minuti_G6_Orario { get; set; }
        public decimal Minuti_G7_Orario { get; set; }
        public decimal Minuti_G8_Orario { get; set; }
        public decimal Minuti_G9_Orario { get; set; }
        public decimal Minuti_G10_Orario { get; set; }
        public decimal Minuti_G11_Orario { get; set; }
        public decimal Minuti_G12_Orario { get; set; }
        public decimal Minuti_G13_Orario { get; set; }
        public decimal Minuti_G14_Orario { get; set; }
        public decimal Minuti_G15_Orario { get; set; }
        public decimal Minuti_G16_Orario { get; set; }
        public decimal Minuti_G17_Orario { get; set; }
        public decimal Minuti_G18_Orario { get; set; }
        public decimal Minuti_G19_Orario { get; set; }
        public decimal Minuti_G20_Orario { get; set; }
        public decimal Minuti_G21_Orario { get; set; }
        public decimal Minuti_G22_Orario { get; set; }
        public decimal Minuti_G23_Orario { get; set; }
        public decimal Minuti_G24_Orario { get; set; }
        public decimal Minuti_G25_Orario { get; set; }
        public decimal Minuti_G26_Orario { get; set; }
        public decimal Minuti_G27_Orario { get; set; }
        public decimal Minuti_G28_Orario { get; set; }
        public decimal Minuti_G29_Orario { get; set; }
        public decimal Minuti_G30_Orario { get; set; }
        public decimal Minuti_G31_Orario { get; set; }
    
        public virtual Col Col { get; set; }
        public virtual Cant Cant { get; set; }
    }
}
