//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Col_Note
    {
        public int Col_Note_Id { get; set; }
        public int Col_Id { get; set; }
        public System.DateTime DataOraUltimaModifica_Col_Note { get; set; }
        public System.DateTime Data_Nota_Col_Note { get; set; }
        public System.DateTime Data_Registrazione_Col_Note { get; set; }
        public bool DisAbilitazione_Col_Note { get; set; }
        public int Utenti_Id { get; set; }
        public string Nota_Col_Note { get; set; }
        public string Tipo_Nota_Col_Note { get; set; }
    
        public virtual Col Col { get; set; }
        public virtual Utenti Utenti { get; set; }
    }
}
