//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Col_Monte_Minuti
    {
        public int Col_Monte_Minuti_Id { get; set; }
        public int Anno_Col_Monte_Minuti { get; set; }
        public int Col_Id { get; set; }
        public int M01_Col_Monte_Minuti { get; set; }
        public int M02_Col_Monte_Minuti { get; set; }
        public int M03_Col_Monte_Minuti { get; set; }
        public int M04_Col_Monte_Minuti { get; set; }
        public int M05_Col_Monte_Minuti { get; set; }
        public int M06_Col_Monte_Minuti { get; set; }
        public int M07_Col_Monte_Minuti { get; set; }
        public int M08_Col_Monte_Minuti { get; set; }
        public int M09_Col_Monte_Minuti { get; set; }
        public int M10_Col_Monte_Minuti { get; set; }
        public int M11_Col_Monte_Minuti { get; set; }
        public int M12_Col_Monte_Minuti { get; set; }
    
        public virtual Col Col { get; set; }
    }
}
