//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Col_V
    {
        public int Col_Id { get; set; }
        public Nullable<short> Arrot_Durata_Col { get; set; }
        public Nullable<short> ArrotF_Col { get; set; }
        public Nullable<short> ArrotI_Col { get; set; }
        public bool Assegni_Famigliari_Col { get; set; }
        public Nullable<System.DateTime> Assegni_Famigliari_Fine_Col { get; set; }
        public Nullable<System.DateTime> Assegni_Famigliari_Inizio_Col { get; set; }
        public bool Automunito_Col { get; set; }
        public Nullable<int> Cant_Id { get; set; }
        public string Codice_Collaboratore { get; set; }
        public string Codice_Domicilio_Luogo_Col { get; set; }
        public string Codice_Fiscale_Col { get; set; }
        public string Codice_Iban_Col { get; set; }
        public string Codice_Nascita_Luogo_Col { get; set; }
        public string Codice_Residenza_Luogo_Col { get; set; }
        public string Cognome_Col { get; set; }
        public Nullable<System.DateTime> Data_Disponibilita_Fine_Col { get; set; }
        public Nullable<System.DateTime> Data_Disponibilita_Inizio_Col { get; set; }
        public System.DateTime Data_Registrazione_Col { get; set; }
        public Nullable<System.DateTime> Data_Sorv_San_Col { get; set; }
        public System.DateTime DataOraUltimaModifica_Col { get; set; }
        public bool Disabile_Col { get; set; }
        public bool DisAbilitazione_Col { get; set; }
        public string Domicilio_Cap_Col { get; set; }
        public string Domicilio_Indirizzo_Col { get; set; }
        public string Domicilio_Localita_Col { get; set; }
        public string Domicilio_Luogo_Col { get; set; }
        public string Domicilio_Provincia_Col { get; set; }
        public Nullable<System.TimeSpan> Durata_Max_Gruppo_Notte_Ril_Col { get; set; }
        public Nullable<System.TimeSpan> Durata_Max_Gruppo_Ril_Col { get; set; }
        public Nullable<System.TimeSpan> Durata_Max_Ril_Col { get; set; }
        public Nullable<System.TimeSpan> Durata_Min_Ril_Col { get; set; }
        public Nullable<System.TimeSpan> Durata_Pausa_Col { get; set; }
        public Nullable<System.TimeSpan> Fascia_Ore_Viaggi_1_Fine_Col { get; set; }
        public Nullable<System.TimeSpan> Fascia_Ore_Viaggi_2_Fine_Col { get; set; }
        public Nullable<System.TimeSpan> Fascia_Ore_Viaggi_3_Fine_Col { get; set; }
        public Nullable<System.TimeSpan> Fascia_Ore_Viaggi_4_Fine_Col { get; set; }
        public Nullable<System.TimeSpan> Fascia_Ore_Viaggi_5_Fine_Col { get; set; }
        public Nullable<System.TimeSpan> Fascia_Ore_Viaggi_1_Inizio_Col { get; set; }
        public Nullable<System.TimeSpan> Fascia_Ore_Viaggi_2_Inizio_Col { get; set; }
        public Nullable<System.TimeSpan> Fascia_Ore_Viaggi_3_Inizio_Col { get; set; }
        public Nullable<System.TimeSpan> Fascia_Ore_Viaggi_4_Inizio_Col { get; set; }
        public Nullable<System.TimeSpan> Fascia_Ore_Viaggi_5_Inizio_Col { get; set; }
        public string Fax_1_Col { get; set; }
        public string Fax_2_Col { get; set; }
        public string Fax_2_Rif_Col { get; set; }
        public string Flag_INPS_Col { get; set; }
        public Nullable<byte> Flag_NON_Esportare_Col { get; set; }
        public Nullable<int> Flag_Ore_Viaggi_Col { get; set; }
        public Nullable<int> Flag_Ore_Viaggi_Col_Inizio_Fine { get; set; }
        public bool Flag_Monte_Ore { get; set; }
        public Nullable<byte> GGConsMax_Col { get; set; }
        public Nullable<double> Indennita_Sanificazione_Col { get; set; }
        public Nullable<double> Indennita_Trasporto_Col { get; set; }
        public string Libretto_Sanitario_Col { get; set; }
        public Nullable<System.TimeSpan> Limite_Inizio_Notte_Col { get; set; }
        public string Livello_Col { get; set; }
        public string Matricola_Col { get; set; }
        public int Metodo_Arrotondamento_Col { get; set; }
        public Nullable<short> Minuti_Arrot_Durata_Fig_Col { get; set; }
        public int Monte_Minuti { get; set; }
        public Nullable<double> N_Persone_A_Carico_Col { get; set; }
        public string N_Pos_INAIL_Col { get; set; }
        public string N_Pos_INPS_Col { get; set; }
        public string Nascita_Cap_Col { get; set; }
        public Nullable<System.DateTime> Nascita_Data_Col { get; set; }
        public string Nascita_Luogo_Col { get; set; }
        public string Nascita_Provincia_Col { get; set; }
        public string Nazionalita_Col { get; set; }
        public string Nome_Col { get; set; }
        public string Note_Col { get; set; }
        public bool NottAbi_Col { get; set; }
        public Nullable<short> OreMassime { get; set; }
        public Nullable<System.TimeSpan> OreMaxGG_Col { get; set; }
        public string Patente_Col { get; set; }
        public Nullable<byte> Prova { get; set; }
        public string Qualifica_Col { get; set; }
        public Nullable<float> Quota_PTime_Col { get; set; }
        public string Raggruppamento1_Col { get; set; }
        public string Residenza_Cap_Col { get; set; }
        public string Residenza_Indirizzo_Col { get; set; }
        public string Residenza_Interno_Col { get; set; }
        public string Residenza_Localita_Col { get; set; }
        public string Residenza_Luogo_Col { get; set; }
        public string Residenza_Provincia_Col { get; set; }
        public Nullable<int> Resp_Id { get; set; }
        public Nullable<double> Retribuzione_Netta_Col { get; set; }
        public Nullable<double> Retribuzione_Lorda_Col { get; set; }
        public Nullable<double> Retribuzione_Oraria_Col { get; set; }
        public Nullable<double> Retribuzione_Straordinaria_Col { get; set; }
        public Nullable<System.DateTime> Scadenza_Patente_Col { get; set; }
        public string Sesso_Col { get; set; }
        public bool Singola_Reg { get; set; }
        public Nullable<short> Soglia_Arrot_Durata_Fig_Col { get; set; }
        public Nullable<short> Soglia_Durata_Col { get; set; }
        public Nullable<short> SogliaF_Col { get; set; }
        public Nullable<short> SogliaI_Col { get; set; }
        public string Stato_Civile_Col { get; set; }
        public bool Straniero_CEE_Col { get; set; }
        public bool Straniero_Col { get; set; }
        public Nullable<System.DateTime> Straniero_Scadenza_Permesso_Col { get; set; }
        public string Telefono_1_Col { get; set; }
        public string Telefono_1_Rif_Col { get; set; }
        public string Telefono_2_Col { get; set; }
        public string Telefono_2_Rif_Col { get; set; }
        public string Telefono_3_Col { get; set; }
        public string Telefono_3_Rif_Col { get; set; }
        public string Telefono_4_Col { get; set; }
        public string Telefono_4_Rif_Col { get; set; }
        public int Tipo_Arrotondamento_Col { get; set; }
        public string Tipo_Col { get; set; }
        public Nullable<int> Tab_Orari_Tipo_Id { get; set; }
        public string Tipo_Rapporto_Col { get; set; }
        public string Tipo_Contratto_Col { get; set; }
        public int TipoNotturno_Col { get; set; }
        public string Titolo_Studio_Col { get; set; }
        public Nullable<double> Trattenuta_Vitto_Col { get; set; }
        public string Zona_Col { get; set; }
        public string Domicilio_Interno_Col { get; set; }
        public string Fax_1_Rif_Col { get; set; }
        public string Raggruppamento2_Col { get; set; }
        public string Residenza_Provincia_GEN_Col { get; set; }
    }
}
