//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Damage
    {
        public int Damage_Id { get; set; }
        public string Codice_Damage { get; set; }
        public int Pru_Id { get; set; }
        public int Fru_Id { get; set; }
        public Nullable<int> Col_Id { get; set; }
        public Nullable<int> Cant_Id { get; set; }
        public int Tab_Damage_Id { get; set; }
        public System.DateTime Data_Registrazione_Damage { get; set; }
        public System.DateTime Data_Ora_Damage { get; set; }
        public string Note_Damage { get; set; }
        public Nullable<bool> Pdf_Attachment { get; set; }
        public Nullable<bool> Audio_Attachment { get; set; }
        public Nullable<bool> Image_Attachment { get; set; }
        public string MultimediaFileName { get; set; }
        public int Tab_Decod_Id { get; set; }
    
        public virtual Cant Cant { get; set; }
        public virtual Col Col { get; set; }
        public virtual Fru Fru { get; set; }
        public virtual Pru Pru { get; set; }
        public virtual Tab_Damage Tab_Damage { get; set; }
        public virtual Tab_Decod Tab_Decod { get; set; }
    }
}
