//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fil
    {
        public Fil()
        {
            this.Utenti_Fil = new HashSet<Utenti_Fil>();
            this.Cant = new HashSet<Cant>();
        }
    
        public int Fil_Id { get; set; }
        public string Codice_Fil { get; set; }
        public System.DateTime Data_Registrazione_Fil { get; set; }
        public System.DateTime DataOraUltimaModifica_Fil { get; set; }
        public string Descrizione_Fil { get; set; }
        public bool DisAbilitazione_Fil { get; set; }
        public string Note_Fil { get; set; }
    
        public virtual ICollection<Utenti_Fil> Utenti_Fil { get; set; }
        public virtual ICollection<Cant> Cant { get; set; }
    }
}
