//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fil
    {
        public Fil()
        {
            this.Cant = new HashSet<Cant>();
            this.Utenti_Fil = new HashSet<Utenti_Fil>();
        }
    
        public int Fil_Id { get; set; }
        public string Codice_Fil { get; set; }
        public System.DateTime Data_Registrazione_Fil { get; set; }
        public System.DateTime DataOraUltimaModifica_Fil { get; set; }
        public string Descrizione_Fil { get; set; }
        public bool DisAbilitazione_Fil { get; set; }
        public string Note_Fil { get; set; }
    
        public virtual ICollection<Cant> Cant { get; set; }
        public virtual ICollection<Utenti_Fil> Utenti_Fil { get; set; }
    }
}
