//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fru
    {
        public Fru()
        {
            this.Damage = new HashSet<Damage>();
            this.Fru_Cant = new HashSet<Fru_Cant>();
            this.PendingElab = new HashSet<PendingElab>();
            this.Reg = new HashSet<Reg>();
        }
    
        public int Fru_Id { get; set; }
        public string Codice_Fru { get; set; }
        public System.DateTime Data_Registrazione_Fru { get; set; }
        public System.DateTime DataOraUltimaModifica_Fru { get; set; }
        public bool DisAbilitazione_Fru { get; set; }
        public string N_Serie_Fru { get; set; }
        public string Note_Fru { get; set; }
        public bool Singola_Reg_Fru { get; set; }
    
        public virtual ICollection<Damage> Damage { get; set; }
        public virtual ICollection<Fru_Cant> Fru_Cant { get; set; }
        public virtual ICollection<PendingElab> PendingElab { get; set; }
        public virtual ICollection<Reg> Reg { get; set; }
    }
}
