//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fru_Cant
    {
        public int Fru_Cant_Id { get; set; }
        public System.DateTime Abilitazione_Data_Inizio_Fru_Can { get; set; }
        public int Cant_Id { get; set; }
        public System.DateTime DataOraUltimaModifica_Fru_Can { get; set; }
        public System.DateTime Data_Registrazione_Fru_Can { get; set; }
        public bool DisAbilitazione_Fru_Can { get; set; }
        public int Fru_Id { get; set; }
        public string Note_Fru_Can { get; set; }
    
        public virtual Cant Cant { get; set; }
        public virtual Fru Fru { get; set; }
    }
}
