//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fru_Cant
    {
        public int Fru_Cant_Id { get; set; }
        public System.DateTime Abilitazione_Data_Inizio_Fru_Can { get; set; }
        public int Cant_Id { get; set; }
        public System.DateTime DataOraUltimaModifica_Fru_Can { get; set; }
        public System.DateTime Data_Registrazione_Fru_Can { get; set; }
        public bool DisAbilitazione_Fru_Can { get; set; }
        public int Fru_Id { get; set; }
        public string Note_Fru_Can { get; set; }
    
        public virtual Fru Fru { get; set; }
        public virtual Cant Cant { get; set; }
    }
}
