//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lingue
    {
        public Lingue()
        {
            this.Resources = new HashSet<Resources>();
            this.Utenti = new HashSet<Utenti>();
        }
    
        public int Lingue_Id { get; set; }
        public System.DateTime Data_Registrazione_Lingue { get; set; }
        public System.DateTime DataOraUltimaModifica_Lingue { get; set; }
        public bool DisAbilitazione_Lingue { get; set; }
        public string Nome_Lingue { get; set; }
        public string Sigla_Lingue { get; set; }
    
        public virtual ICollection<Resources> Resources { get; set; }
        public virtual ICollection<Utenti> Utenti { get; set; }
    }
}
