//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.Children = new HashSet<Menu>();
        }
    
        public int Menu_Id { get; set; }
        public Nullable<int> Menu_Tipo_Id { get; set; }
        public Nullable<int> Parent_Id { get; set; }
        public int Ordering { get; set; }
        public Nullable<int> Tab_Funz_Id { get; set; }
        public string Testo { get; set; }
    
        public virtual ICollection<Menu> Children { get; set; }
        public virtual Menu Parent { get; set; }
        public virtual Menu_Tipo Menu_Tipo { get; set; }
        public virtual Tab_Funz Tab_Funz { get; set; }
    }
}
