//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.Children = new HashSet<Menu>();
        }
    
        public int Menu_Id { get; set; }
        public Nullable<int> Menu_Tipo_Id { get; set; }
        public Nullable<int> Parent_Id { get; set; }
        public int Ordering { get; set; }
        public Nullable<int> Tab_Funz_Id { get; set; }
        public string Testo { get; set; }
    
        public virtual ICollection<Menu> Children { get; set; }
        public virtual Menu Parent { get; set; }
        public virtual Menu_Tipo Menu_Tipo { get; set; }
        public virtual Tab_Funz Tab_Funz { get; set; }
    }
}
