//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_Tipo
    {
        public Menu_Tipo()
        {
            this.Menu = new HashSet<Menu>();
            this.Utenti1 = new HashSet<Utenti>();
        }
    
        public int Menu_Tipo_Id { get; set; }
        public string Nome_Risorsa_Menu_Tipo { get; set; }
        public Nullable<int> Utenti_Id { get; set; }
        public Nullable<bool> Tipo_Standard { get; set; }
    
        public virtual ICollection<Menu> Menu { get; set; }
        public virtual Utenti Utenti { get; set; }
        public virtual ICollection<Utenti> Utenti1 { get; set; }
    }
}
