//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_Tipo
    {
        public Menu_Tipo()
        {
            this.Menu = new HashSet<Menu>();
            this.Utenti1 = new HashSet<Utenti>();
        }
    
        public int Menu_Tipo_Id { get; set; }
        public string Nome_Risorsa_Menu_Tipo { get; set; }
        public Nullable<int> Utenti_Id { get; set; }
        public Nullable<bool> Tipo_Standard { get; set; }
    
        public virtual ICollection<Menu> Menu { get; set; }
        public virtual Utenti Utenti { get; set; }
        public virtual ICollection<Utenti> Utenti1 { get; set; }
    }
}
