//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetaFieldDescriptor
    {
        public int MetaFieldDescriptorId { get; set; }
        public int MetaDescriptorId { get; set; }
        public string FieldName { get; set; }
        public int GridViewDataType { get; set; }
        public bool IsAvailable { get; set; }
        public bool IsVisible { get; set; }
        public bool IsVibile_EditFormSettings { get; set; }
        public bool IsReadOnly { get; set; }
        public Nullable<int> VisibleIndex { get; set; }
        public string Width { get; set; }
        public string Mask { get; set; }
        public int IncludeLiterals { get; set; }
        public string DisplayFormatString { get; set; }
        public int HorizontalAlign { get; set; }
        public int EditFormat { get; set; }
        public int DecimalPlaces { get; set; }
        public bool AllowHeaderFilter { get; set; }
    
        public virtual MetaDescriptor MetaDescriptor { get; set; }
    }
}
