//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetaDescriptor
    {
        public MetaDescriptor()
        {
            this.MetaFieldDescriptor = new HashSet<MetaFieldDescriptor>();
        }
    
        public int MetaDescriptorId { get; set; }
        public string EntityType { get; set; }
    
        public virtual ICollection<MetaFieldDescriptor> MetaFieldDescriptor { get; set; }
    }
}
