//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetaFieldDescriptor
    {
        public int MetaFieldDescriptorId { get; set; }
        public int MetaDescriptorId { get; set; }
        public string FieldName { get; set; }
        public int GridViewDataType { get; set; }
        public bool IsAvailable { get; set; }
        public bool IsVisible { get; set; }
        public bool IsVibile_EditFormSettings { get; set; }
        public bool IsReadOnly { get; set; }
        public Nullable<int> VisibleIndex { get; set; }
        public string Width { get; set; }
        public string Mask { get; set; }
        public int IncludeLiterals { get; set; }
        public string DisplayFormatString { get; set; }
        public int HorizontalAlign { get; set; }
        public int EditFormat { get; set; }
        public int DecimalPlaces { get; set; }
        public bool AllowHeaderFilter { get; set; }
    
        public virtual MetaDescriptor MetaDescriptor { get; set; }
    }
}
