//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetaDescriptor
    {
        public MetaDescriptor()
        {
            this.MetaFieldDescriptor = new HashSet<MetaFieldDescriptor>();
        }
    
        public int MetaDescriptorId { get; set; }
        public string EntityType { get; set; }
    
        public virtual ICollection<MetaFieldDescriptor> MetaFieldDescriptor { get; set; }
    }
}
