//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Param
    {
        public int Param_Id { get; set; }
        public string ActivationDate { get; set; }
        public bool Abilita_Arrotondamenti { get; set; }
        public bool Abilita_Att { get; set; }
        public bool Abilita_Aut_Str { get; set; }
        public bool Abilita_Cartellino { get; set; }
        public bool Abilita_Confronto_Ore_Budget { get; set; }
        public bool Abilita_GPS { get; set; }
        public bool Abilita_Monte_Minuti { get; set; }
        public bool Abilita_Notifiche { get; set; }
        public bool Abilita_Notturno { get; set; }
        public bool Abilita_Orari { get; set; }
        public bool Abilita_Pass { get; set; }
        public bool Abilita_Privacy { get; set; }
        public bool Abilita_Schedulatore { get; set; }
        public bool Abilita_Viaggi { get; set; }
        public bool Abilita_Where_Is_It { get; set; }
        public bool Attiva_Num_Aut_Can { get; set; }
        public bool Attiva_Num_Aut_Col { get; set; }
        public Nullable<int> Aut_Str_Tipo { get; set; }
        public string BingKey { get; set; }
        public Nullable<int> Cant_Id { get; set; }
        public Nullable<int> Cantiere_Timbrature_GPS_Non_Valide { get; set; }
        public bool Cartellino_Divisione_Piano_Notturno_Diurno { get; set; }
        public bool Cartellino_Visualizza_Arrotondamenti { get; set; }
        public bool Cartellino_Visualizza_Piano { get; set; }
        public bool Cartellino_Visualizza_Ore { get; set; }
        public bool Cartellino_Visualizza_Motivazioni { get; set; }
        public bool Cartellino_Visualizza_Delta { get; set; }
        public bool Cartellino_Visualizza_Totale { get; set; }
        public Nullable<System.TimeSpan> Cartellino_Inizio_Notturno { get; set; }
        public Nullable<System.TimeSpan> Cartellino_Fine_Notturno { get; set; }
        public bool Cartellino_Visualizza_Viaggi { get; set; }
        public bool Cartellino_Usa_Cartellino_Modificabile { get; set; }
        public bool Cartellino_Modalita_Compatta { get; set; }
        public bool Cartellino_Dividi_Altra_Anagrafica { get; set; }
        public bool Cartellino_Usa_Rettifiche_Cartellino { get; set; }
        public bool Cartellino_Usa_Rettifiche_Manuali { get; set; }
        public bool Cartellino_Usa_Rettifiche_Auto { get; set; }
        public bool Cartellino_Abilita_Stampa_Cart_Editabile { get; set; }
        public bool Cartellino_Abilita_Divisione_Cantiere { get; set; }
        public int Cartellino_Visualizza_Totali_Settimanali { get; set; }
        public bool Cartellino_Totale_Prima_Colonna { get; set; }
        public string Codice_Cliente { get; set; }
        public int ComboBoxDelay { get; set; }
        public int ComboboxRowsPerPage { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyEmail { get; set; }
        public string CompanyInfo { get; set; }
        public byte[] CompanyLogo { get; set; }
        public Nullable<int> Ctrl_Tab_Comuni { get; set; }
        public Nullable<int> Ctrl_Codice_Fisc { get; set; }
        public Nullable<int> Ctrl_Codice_IBAN { get; set; }
        public Nullable<bool> Ctrl_Sovrap_Pass { get; set; }
        public Nullable<System.DateTime> Data_Blocco_Reg { get; set; }
        public System.DateTime Data_Registrazione { get; set; }
        public Nullable<System.DateTime> Data_Stored_Reg { get; set; }
        public System.DateTime DataOraUltimaModifica { get; set; }
        public bool Default_Abilitati { get; set; }
        public Nullable<System.TimeSpan> Default_Durata_Giornata { get; set; }
        public Nullable<System.TimeSpan> Default_Ora_Inizio_Giornata { get; set; }
        public Nullable<System.TimeSpan> Default_Durata_Max_Gruppo_Notte_Ril { get; set; }
        public Nullable<System.TimeSpan> Default_Durata_Max_Gruppo_Ril { get; set; }
        public Nullable<System.TimeSpan> Default_Durata_Max_Ril { get; set; }
        public Nullable<System.TimeSpan> Default_Durata_Min_Ril { get; set; }
        public Nullable<short> Default_Minuti_Arrot_I { get; set; }
        public Nullable<short> Default_Minuti_Arrot_F { get; set; }
        public Nullable<short> Default_Minuti_Durata { get; set; }
        public Nullable<short> Default_Soglia_Arrot_I { get; set; }
        public Nullable<short> Default_Soglia_Arrot_F { get; set; }
        public Nullable<short> Default_Soglia_Durata { get; set; }
        public bool Dflt_DoRefresh_Grid { get; set; }
        public bool Dflt_Include_Activities { get; set; }
        public bool Dflt_Include_Blocked { get; set; }
        public bool Dflt_Include_Pass { get; set; }
        public bool Dflt_Include_Trips { get; set; }
        public int DomainFilter { get; set; }
        public Nullable<System.TimeSpan> Durata_Quadratura_Rettifiche_Auto { get; set; }
        public Nullable<System.TimeSpan> Durata_Massima_Viaggio { get; set; }
        public Nullable<System.TimeSpan> Durata_Minima_Viaggio { get; set; }
        public Nullable<System.TimeSpan> Durata_Notturno { get; set; }
        public Nullable<System.TimeSpan> Durata_Pausa { get; set; }
        public bool Elaborate_Semaforo { get; set; }
        public Nullable<System.TimeSpan> Fascia_Ore_Viaggi_1_Inizio { get; set; }
        public Nullable<System.TimeSpan> Fascia_Ore_Viaggi_1_Fine { get; set; }
        public Nullable<System.TimeSpan> Fascia_Ore_Viaggi_2_Inizio { get; set; }
        public Nullable<System.TimeSpan> Fascia_Ore_Viaggi_2_Fine { get; set; }
        public Nullable<System.TimeSpan> Fascia_Ore_Viaggi_3_Inizio { get; set; }
        public Nullable<System.TimeSpan> Fascia_Ore_Viaggi_3_Fine { get; set; }
        public Nullable<System.TimeSpan> Fascia_Ore_Viaggi_4_Inizio { get; set; }
        public Nullable<System.TimeSpan> Fascia_Ore_Viaggi_4_Fine { get; set; }
        public Nullable<System.TimeSpan> Fascia_Ore_Viaggi_5_Inizio { get; set; }
        public Nullable<System.TimeSpan> Fascia_Ore_Viaggi_5_Fine { get; set; }
        public bool File_Cant_Var { get; set; }
        public bool File_Col_Var { get; set; }
        public bool Flag_Calcolo_Viaggi { get; set; }
        public int Flag_GPS { get; set; }
        public Nullable<int> Flag_Ore_Viaggi { get; set; }
        public Nullable<int> Flag_Ore_Viaggi_Inizio_Fine { get; set; }
        public int Flag_Monte_Ore { get; set; }
        public Nullable<short> GG_X_Allarmi { get; set; }
        public Nullable<bool> Gestione_SottoCantieri { get; set; }
        public string Importazione_timbrature_GPS { get; set; }
        public Nullable<System.TimeSpan> Limite_Entrata_Mattina { get; set; }
        public Nullable<System.TimeSpan> Limite_Entrata_Pomeriggio { get; set; }
        public Nullable<System.TimeSpan> Limite_Entrata_Inizio_Pomeriggio { get; set; }
        public bool Limite_Entrata_Usa_Orario { get; set; }
        public int MaxElab_ImportChunkSize { get; set; }
        public string MDBPath { get; set; }
        public byte Mesi_Validita_Reg { get; set; }
        public int Metodo_Arrotondamento { get; set; }
        public int ModuleType { get; set; }
        public Nullable<bool> Pausa_Viaggio { get; set; }
        public string PercorsoFotoCol { get; set; }
        public string PublicKey { get; set; }
        public Nullable<double> RaggioGpsDefault { get; set; }
        public Nullable<int> Ritardo_Tolleranza_Minuti { get; set; }
        public int RowsPerComboBox { get; set; }
        public int RowsPerPage { get; set; }
        public bool Sabato_Feriale { get; set; }
        public Nullable<int> StoredChunkSize { get; set; }
        public Nullable<short> Tempo_Doppia_Reg { get; set; }
        public int Tipo_Arrotondamento { get; set; }
        public int Tipo_Assegnazione_KMMinuti { get; set; }
        public int Tipo_Assegnazione_KMMinuti_Inizio_Fine_G { get; set; }
        public string Tipo_Ass_Tag_Gps { get; set; }
        public string Tipo_Chiusura_Causali { get; set; }
        public int Tipo_Monte_Ore { get; set; }
        public int TipoNotturno { get; set; }
        public byte Tipo_Viaggio { get; set; }
        public Nullable<System.TimeSpan> Tolleranza_Limite_Entrata_Pomeriggio { get; set; }
        public int Utilizzo_Limite_Entrata { get; set; }
        public Nullable<byte> Utilizzo_Fasce_Viaggi { get; set; }
        public bool Cartellino_Abilita_Modifica { get; set; }
        public bool Sincronizzazione_ClockApp { get; set; }
        public string Url_ClockAppsManager { get; set; }
        public bool BlockLoginOnUserPswExpired { get; set; }
        public Nullable<int> PasswordExpirationDays { get; set; }
        public bool ImportaFileTimbratureSospese { get; set; }
        public int Utilizzo_Limite_Uscita { get; set; }
        public Nullable<System.TimeSpan> Limite_Uscita_Pomeriggio { get; set; }
        public Nullable<System.TimeSpan> Limite_Uscita_Mattina { get; set; }
        public bool Limite_Uscita_Usa_Orario { get; set; }
        public Nullable<System.TimeSpan> Tolleranza_Limite_Uscita_Pomeriggio { get; set; }
        public Nullable<System.TimeSpan> Tolleranza_Limite_Uscita_Mattina { get; set; }
        public int Indice_Timbrature_GeoBadge { get; set; }
        public bool Abilita_Sincronizzazione_Entità { get; set; }
        public bool Abilita_Import_Esterno { get; set; }
        public Nullable<short> Soglia_Minima_Arrotondamento_Durata { get; set; }
        public Nullable<int> Tolleranza_Limite_Entrata { get; set; }

        public virtual Cant Cant { get; set; }
    }
}
