//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PendingElab
    {
        public int PendingElab_Id { get; set; }
        public Nullable<System.DateTime> FromDate_PendingElab { get; set; }
        public Nullable<System.DateTime> ToDate_PendingElab { get; set; }
        public Nullable<int> Pru_Id { get; set; }
        public Nullable<int> Fru_Id { get; set; }
        public Nullable<System.DateTime> ElaborateDate_PendingElab { get; set; }
    
        public virtual Fru Fru { get; set; }
        public virtual Pru Pru { get; set; }
    }
}
