//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PendingElab
    {
        public int PendingElab_Id { get; set; }
        public Nullable<System.DateTime> FromDate_PendingElab { get; set; }
        public Nullable<System.DateTime> ToDate_PendingElab { get; set; }
        public Nullable<int> Pru_Id { get; set; }
        public Nullable<int> Fru_Id { get; set; }
        public Nullable<System.DateTime> ElaborateDate_PendingElab { get; set; }
    
        public virtual Fru Fru { get; set; }
        public virtual Pru Pru { get; set; }
    }
}
