//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pru
    {
        public Pru()
        {
            this.Damage = new HashSet<Damage>();
            this.PendingElab = new HashSet<PendingElab>();
            this.Pru_Col = new HashSet<Pru_Col>();
            this.Reg = new HashSet<Reg>();
        }
    
        public int Pru_Id { get; set; }
        public string Codice_Pru { get; set; }
        public System.DateTime Data_Registrazione_Pru { get; set; }
        public System.DateTime DataOraUltimaModifica_Pru { get; set; }
        public bool DisAbilitazione_Pru { get; set; }
        public string N_Serie_Pru { get; set; }
        public string Note_Pru { get; set; }
        public bool Singola_Reg_Pru { get; set; }
    
        public virtual ICollection<Damage> Damage { get; set; }
        public virtual ICollection<PendingElab> PendingElab { get; set; }
        public virtual ICollection<Pru_Col> Pru_Col { get; set; }
        public virtual ICollection<Reg> Reg { get; set; }
    }
}
