//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pru_Col
    {
        public int Pru_Col_Id { get; set; }
        public System.DateTime Abilitazione_Data_Inizio_Pru_Col { get; set; }
        public int Col_Id { get; set; }
        public System.DateTime DataOraUltimaModifica_Pru_Col { get; set; }
        public System.DateTime Data_Registrazione_Pru_Col { get; set; }
        public bool DisAbilitazione_Pru_Col { get; set; }
        public int Pru_Id { get; set; }
        public string Note_Pru_Col { get; set; }
    
        public virtual Col Col { get; set; }
        public virtual Pru Pru { get; set; }
    }
}
