//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reg
    {
        public Reg()
        {
            this.Regs = new HashSet<Reg>();
        }
    
        public int Reg_Id { get; set; }
        public Nullable<int> Cant_Id { get; set; }
        public Nullable<int> Col_Id { get; set; }
        public string Custom_Data_Reg { get; set; }
        public System.DateTime Data_Registrazione_Reg { get; set; }
        public System.DateTime DataOraUltimaModifica_Reg { get; set; }
        public bool DisAbilitazione_Reg { get; set; }
        public string Flag_EU_Reg { get; set; }
        public Nullable<int> Fru_Id { get; set; }
        public bool IsNotToElaborate { get; set; }
        public Nullable<decimal> KM_Reg { get; set; }
        public Nullable<int> Motivazione_Reg_Id { get; set; }
        public string Note_Reg { get; set; }
        public Nullable<int> Pru_Id { get; set; }
        public Nullable<System.DateTime> Registrazione_Data_Ora_Fig_Reg { get; set; }
        public System.DateTime Registrazione_Data_Ora_Orig_Reg { get; set; }
        public System.DateTime Registrazione_Data_Ora_Fis_Reg { get; set; }
        public int Registrazione_Tipo_Reg { get; set; }
        public Nullable<int> RiferimentoRRN_Reg { get; set; }
        public int Registrazione_Stato_Reg { get; set; }
        public Nullable<int> RiferimentoRRN_Att { get; set; }
        public Nullable<System.TimeSpan> Ore_Calc_Reg { get; set; }
        public Nullable<int> Att_Id { get; set; }
        public bool Registrazione_Bloccata { get; set; }
        public string Codice_Accoppiamento { get; set; }
        public Nullable<int> Rettifica_Durata { get; set; }
        public Nullable<double> Registrazione_Lat_Orig { get; set; }
        public Nullable<double> Registrazione_Long_Orig { get; set; }
        public string Registrazione_Badge_Originale { get; set; }
        public Nullable<int> Activity_Evaluation { get; set; }
        public string Tipo_Attivita { get; set; }
        public string Turno { get; set; }
        public string Sotto_Cantiere { get; set; }
        public Nullable<int> Stato_Attivita { get; set; }
        public Nullable<int> Ritardo_Durata { get; set; }
        public bool Ritardo_Mail_Sent { get; set; }
        public Nullable<int> CentroDiCosto_Id { get; set; }
    
        public virtual Cant Cant { get; set; }
        public virtual Col Col { get; set; }
        public virtual Fru Fru { get; set; }
        public virtual Pru Pru { get; set; }
        public virtual ICollection<Reg> Regs { get; set; }
        public virtual Reg ParentReg { get; set; }
        public virtual Tab_Decod Tab_Decod { get; set; }
        public virtual CentroDiCosto CentroDiCosto { get; set; }
    }
}
