//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reg_V
    {
        public int RegE { get; set; }
        public Nullable<int> RegU { get; set; }
        public Nullable<int> CentroDiCosto_Id { get; set; }
        public Nullable<int> Cant_Id { get; set; }
        public string Cant_Mnemonic { get; set; }
        public string Cant_Desc { get; set; }
        public Nullable<bool> DisAbilitazione_Can { get; set; }
        public Nullable<int> Col_Id { get; set; }
        public string Col_Mnemonic { get; set; }
        public string Col_Desc { get; set; }
        public Nullable<bool> DisAbilitazione_Col { get; set; }
        public Nullable<int> Pru_Id { get; set; }
        public string Codice_Pru { get; set; }
        public Nullable<int> Fru_Id { get; set; }
        public string Codice_Fru { get; set; }
        public Nullable<int> Motivazione_Reg_Id { get; set; }
        public string Motivazione_Reg_Cod { get; set; }
        public string Registrazione_Tipo_Desc { get; set; }
        public Nullable<System.DateTime> Data_Ora_Fig_E { get; set; }
        public Nullable<System.DateTime> Data_Ora_Fig_U { get; set; }
        public Nullable<int> Durata_Fig { get; set; }
        public System.DateTime Data_Ora_Fis_E { get; set; }
        public Nullable<System.DateTime> Data_Ora_Fis_U { get; set; }
        public Nullable<int> Durata_Fis { get; set; }
        public Nullable<System.TimeSpan> Data_Ora_Fig_ETime { get; set; }
        public Nullable<System.TimeSpan> Data_Ora_Fis_ETime { get; set; }
        public Nullable<System.TimeSpan> Data_Ora_Fig_UTime { get; set; }
        public Nullable<System.TimeSpan> Data_Ora_Fis_UTime { get; set; }
        public Nullable<System.DateTime> Data_Ora_Fig_EDate { get; set; }
        public Nullable<System.DateTime> Data_Reg { get; set; }
        public string Durata_Fis_HH_S { get; set; }
        public string Durata_Fig_HH_S { get; set; }
        public int Tipo_Modifica { get; set; }
        public Nullable<decimal> KM_Reg { get; set; }
        public Nullable<System.TimeSpan> Ore_Calc_Reg { get; set; }
        public string Note_Reg { get; set; }
        public bool IsNotToElaborate { get; set; }
        public int Registrazione_Tipo_Reg { get; set; }
        public int Registrazione_Stato_Reg { get; set; }
        public Nullable<int> RiferimentoRRN_Att { get; set; }
        public Nullable<int> Resp_Id { get; set; }
        public Nullable<int> Fil_Id { get; set; }
        public Nullable<int> Data_Reg_AAAA { get; set; }
        public string Data_Reg_AAAA_MM { get; set; }
        public Nullable<int> Att_Id { get; set; }
        public bool Registrazione_Bloccata { get; set; }
        public string EntrataEU { get; set; }
        public string UscitaEU { get; set; }
        public Nullable<double> Registrazione_Lat_Orig_E { get; set; }
        public Nullable<double> Registrazione_Long_Orig_E { get; set; }
        public Nullable<double> Registrazione_Lat_Orig_U { get; set; }
        public Nullable<double> Registrazione_Long_Orig_U { get; set; }
        public Nullable<int> Cli_Id { get; set; }
        public string Codice_Commessa_Can { get; set; }
        public string Qualifica_Col { get; set; }
        public string Codice_Gestionale_Can { get; set; }
        public Nullable<int> Att_Cli_Id { get; set; }
        public Nullable<int> Activity_Evaluation { get; set; }
        public string Delta_Fig_Fis { get; set; }
        public Nullable<int> Stato_Attivita { get; set; }
        public string Tipo_Attivita { get; set; }
        public string Sotto_Cantiere { get; set; }
        public string Turno { get; set; }
        public string Codice_Cliente { get; set; }
        public string Cognome_Cli { get; set; }
        public string Nome_Cli { get; set; }
        public Nullable<int> Ritardo_Durata { get; set; }
        public bool Ritardo_Mail_Sent { get; set; }
        public string N_Serie_Fru { get; set; }
        public Nullable<double> Costo_Orario_Fig { get; set; }
        public Nullable<double> Costo_Orario_Fis { get; set; }
    }
}
