//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resources
    {
        public int Resources_Id { get; set; }
        public int Lingue_Id { get; set; }
        public Nullable<int> Versioni_Id { get; set; }
        public string ResourceKey { get; set; }
        public string ResourceValue { get; set; }
    
        public virtual Lingue Lingue { get; set; }
        public virtual Versioni Versioni { get; set; }
    }
}
