//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resources
    {
        public int Resources_Id { get; set; }
        public int Lingue_Id { get; set; }
        public Nullable<int> Versioni_Id { get; set; }
        public string ResourceKey { get; set; }
        public string ResourceValue { get; set; }
    
        public virtual Lingue Lingue { get; set; }
        public virtual Versioni Versioni { get; set; }
    }
}
