//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resp
    {
        public Resp()
        {
            this.Utenti_Resp = new HashSet<Utenti_Resp>();
            this.Col = new HashSet<Col>();
            this.Aut_Str = new HashSet<Aut_Str>();
        }
    
        public int Resp_Id { get; set; }
        public string Codice_Resp { get; set; }
        public System.DateTime Data_Registrazione_Resp { get; set; }
        public System.DateTime DataOraUltimaModifica_Resp { get; set; }
        public string Descrizione_Resp { get; set; }
        public bool DisAbilitazione_Resp { get; set; }
        public string Note_Resp { get; set; }
    
        public virtual ICollection<Utenti_Resp> Utenti_Resp { get; set; }
        public virtual ICollection<Col> Col { get; set; }
        public virtual ICollection<Aut_Str> Aut_Str { get; set; }
    }
}
