//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resp
    {
        public Resp()
        {
            this.Aut_Str = new HashSet<Aut_Str>();
            this.Col = new HashSet<Col>();
            this.Utenti_Resp = new HashSet<Utenti_Resp>();
        }
    
        public int Resp_Id { get; set; }
        public string Codice_Resp { get; set; }
        public System.DateTime Data_Registrazione_Resp { get; set; }
        public System.DateTime DataOraUltimaModifica_Resp { get; set; }
        public string Descrizione_Resp { get; set; }
        public bool DisAbilitazione_Resp { get; set; }
        public string Note_Resp { get; set; }
    
        public virtual ICollection<Aut_Str> Aut_Str { get; set; }
        public virtual ICollection<Col> Col { get; set; }
        public virtual ICollection<Utenti_Resp> Utenti_Resp { get; set; }
    }
}
