//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Orari
    {
        public int Tab_Orari_Id { get; set; }
        public System.DateTime Data_Inizio { get; set; }
        public bool G1 { get; set; }
        public bool G2 { get; set; }
        public bool G3 { get; set; }
        public bool G4 { get; set; }
        public bool G5 { get; set; }
        public bool G6 { get; set; }
        public bool G7 { get; set; }
        public int Sequenza { get; set; }
        public int Ripetizione { get; set; }
        public Nullable<int> Cant_Id { get; set; }
        public int Tab_Orari_Tipo_Id { get; set; }
        public Nullable<System.TimeSpan> Ora_E { get; set; }
        public Nullable<System.TimeSpan> Ora_U { get; set; }
        public int Durata_Minuti { get; set; }
        public bool Usa_Pausa { get; set; }
        public Nullable<int> Col_Id { get; set; }
        public bool Orario_Mensile { get; set; }
    
        public virtual Tab_Orari_Tipo Tab_Orari_Tipo { get; set; }
    }
}
