//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_DataGrid
    {
        public int DataGrid_Id { get; set; }
        public System.DateTime Data_Layout_DataGrid { get; set; }
        public string Layout_DataGrid { get; set; }
        public string Nome_DataGrid { get; set; }
        public string Nome_Layout { get; set; }
        public Nullable<int> Utenti_Id { get; set; }
    
        public virtual Utenti Utenti { get; set; }
    }
}
