//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Dist
    {
        public int Tab_Dist_Id { get; set; }
        public string Arrivo_Tab_Dist { get; set; }
        public decimal KM_Tab_Dist { get; set; }
        public int Minuti_Tab_Dist { get; set; }
        public string Partenza_Tab_Dist { get; set; }
        public int Tab_Decod_Id { get; set; }
    
        public virtual Tab_Decod Tab_Decod { get; set; }
    }
}
