//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Report
    {
        public Tab_Report()
        {
            this.Tab_Report_Group = new HashSet<Tab_Report_Group>();
            this.Tab_Report_Order = new HashSet<Tab_Report_Order>();
        }
    
        public int Report_Id { get; set; }
        public string Classe_Report { get; set; }
        public System.DateTime Data_Layout_Report { get; set; }
        public string Nome_DataGrid { get; set; }
        public string Nome_Report { get; set; }
        public string Nome_Risorsa { get; set; }
        public string Nome_Specializzato { get; set; }
        public string Tab_String { get; set; }
        public Nullable<int> Utenti_Id { get; set; }
    
        public virtual ICollection<Tab_Report_Group> Tab_Report_Group { get; set; }
        public virtual ICollection<Tab_Report_Order> Tab_Report_Order { get; set; }
        public virtual Utenti Utenti { get; set; }
    }
}
