//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Orari_Tipo
    {
        public Tab_Orari_Tipo()
        {
            this.Col = new HashSet<Col>();
            this.Tab_Orari = new HashSet<Tab_Orari>();
            this.Cant = new HashSet<Cant>();
        }
    
        public int Tab_Orari_Tipo_Id { get; set; }
        public string Tab_Orari_Tipo_Desc { get; set; }
        public Nullable<System.TimeSpan> Tab_Orari_Tipo_Inizio_Not { get; set; }
        public Nullable<System.TimeSpan> Tab_Orari_Tipo_Fine_Not { get; set; }
        public string Tab_Orari_Tipo_Entita_Rif { get; set; }
        public bool Tab_Orari_Tipo_NotDiu_Auto { get; set; }
    
        public virtual ICollection<Col> Col { get; set; }
        public virtual ICollection<Tab_Orari> Tab_Orari { get; set; }
        public virtual ICollection<Cant> Cant { get; set; }
    }
}
