//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Prov
    {
        public Tab_Prov()
        {
            this.Tab_Comuni = new HashSet<Tab_Comuni>();
        }
    
        public int Tab_Prov_Id { get; set; }
        public string Sigla_Prov { get; set; }
        public string Descrizione_Prov { get; set; }
    
        public virtual ICollection<Tab_Comuni> Tab_Comuni { get; set; }
    }
}
