//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Prov
    {
        public Tab_Prov()
        {
            this.Tab_Comuni = new HashSet<Tab_Comuni>();
        }
    
        public int Tab_Prov_Id { get; set; }
        public string Sigla_Prov { get; set; }
        public string Descrizione_Prov { get; set; }
    
        public virtual ICollection<Tab_Comuni> Tab_Comuni { get; set; }
    }
}
