//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Festivi
    {
        public int Tab_Festivi_Id { get; set; }
        public string Descrizione_Tab_Festivi { get; set; }
        public System.DateTime Giorno_Tab_Festivi { get; set; }
    }
}
