//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Report_Group
    {
        public int Report_Group_Id { get; set; }
        public string Field { get; set; }
        public bool IsSkipPage { get; set; }
        public bool IsShowHeader { get; set; }
        public int Position { get; set; }
        public int Report_Id { get; set; }
        public bool RepeatEveryPage { get; set; }
    
        public virtual Tab_Report Tab_Report { get; set; }
    }
}
