//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Report_Group
    {
        public int Report_Group_Id { get; set; }
        public string Field { get; set; }
        public bool IsSkipPage { get; set; }
        public bool IsShowHeader { get; set; }
        public int Position { get; set; }
        public int Report_Id { get; set; }
        public bool RepeatEveryPage { get; set; }
    
        public virtual Tab_Report Tab_Report { get; set; }
    }
}
