//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_DataGrid
    {
        public int DataGrid_Id { get; set; }
        public System.DateTime Data_Layout_DataGrid { get; set; }
        public string Layout_DataGrid { get; set; }
        public string Nome_DataGrid { get; set; }
        public string Nome_Layout { get; set; }
        public Nullable<int> Utenti_Id { get; set; }
    
        public virtual Utenti Utenti { get; set; }
    }
}
