//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Damage
    {
        public Tab_Damage()
        {
            this.Damage = new HashSet<Damage>();
        }
    
        public int Tab_Damage_Id { get; set; }
        public string Descrizione_Tab_Damage { get; set; }
        public int Tab_Decod_Id { get; set; }
        public bool DisAbilitazione_Tab_Damage { get; set; }
    
        public virtual ICollection<Damage> Damage { get; set; }
        public virtual Tab_Decod Tab_Decod { get; set; }
    }
}
