//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Aut
    {
        public int Aut_Id { get; set; }
        public System.DateTime DataOraUltimaModifica_Aut { get; set; }
        public System.DateTime Data_Registrazione_Aut { get; set; }
        public int Del_Aut { get; set; }
        public int Funz_Aut { get; set; }
        public int Ins_Aut { get; set; }
        public int Mod_Aut { get; set; }
        public int MsgDel1_Aut { get; set; }
        public int MsgDel2_Aut { get; set; }
        public int MsgIns1_Aut { get; set; }
        public int MsgIns2_Aut { get; set; }
        public int MsgMod1_Aut { get; set; }
        public int MsgMod2_Aut { get; set; }
        public Nullable<int> Utenti_Id { get; set; }
        public Nullable<int> Tab_Funz_Id { get; set; }
    
        public virtual Tab_Funz Tab_Funz { get; set; }
        public virtual Utenti Utenti { get; set; }
    }
}
