//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Festivi
    {
        public int Tab_Festivi_Id { get; set; }
        public string Descrizione_Tab_Festivi { get; set; }
        public System.DateTime Giorno_Tab_Festivi { get; set; }
    }
}
