//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Comuni
    {
        public int Tab_Comuni_Id { get; set; }
        public string Cap_Tab_Comuni { get; set; }
        public string Luogo_Tab_Comuni { get; set; }
        public string Codice_Luogo_Tab_Comuni { get; set; }
        public int Codice_Istat_Tab_Comuni { get; set; }
        public int Tab_Prov_Id { get; set; }
        public string Codice_Prov_Tab_Comuni { get; set; }
    
        public virtual Tab_Prov Tab_Prov { get; set; }
    }
}
