//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Excel_Model
    {
        public int ExcelModel_Id { get; set; }
        public bool IsActive { get; set; }
        public string ModelFilePath { get; set; }
        public string Nome_Entity { get; set; }
        public string Nome_Risorsa { get; set; }
        public string Nome_Specializzato { get; set; }
        public string Tipo_Selezione { get; set; }
        public bool Selezione_Figurative_Fisiche { get; set; }
        public bool Selezione_Solo_Durata_EU { get; set; }
        public bool Selezione_Tolleranza_Durata { get; set; }
        public bool Selezione_Tolleranza_EU { get; set; }
        public bool Utilizza_Solo_Selezione { get; set; }
        public bool Seleziona_Dettagli { get; set; }
        public string Pagina { get; set; }
        public string Extension { get; set; }
        public string FileName { get; set; }
        public bool Selezione_Durata_Cent { get; set; }
        public bool Zip { get; set; }
    }
}
