//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Messaggi
    {
        public int Tab_Messaggi_Id { get; set; }
        public int Applicazione_Tab_Messaggi_Id { get; set; }
        public Nullable<System.DateTime> Data_Ora_Elab_Tab_Messaggi { get; set; }
        public System.DateTime Data_Tab_Messaggi { get; set; }
        public int Funzione_Tab_Messaggi_Id { get; set; }
        public string Testo_Tab_Messaggi { get; set; }
        public Nullable<int> Utente_Id { get; set; }
    
        public virtual Utenti Utenti { get; set; }
    }
}
