//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Funz
    {
        public Tab_Funz()
        {
            this.Menu = new HashSet<Menu>();
            this.Tab_Aut = new HashSet<Tab_Aut>();
        }
    
        public int Tab_Funz_Id { get; set; }
        public int Dflt_Grid_Edit_Mode { get; set; }
        public string Link_Tab_Funz { get; set; }
        public string Nome_Tab_Funz { get; set; }
        public int Dflt_OnOffBtnVisible { get; set; }
    
        public virtual ICollection<Menu> Menu { get; set; }
        public virtual ICollection<Tab_Aut> Tab_Aut { get; set; }
    }
}
