//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Chk_Imp
    {
        public int Tab_Chk_Imp_Id { get; set; }
        public string Nome_Tabella_Tab_Check_Imp { get; set; }
        public string Chiave_Record_Tab_Check_Imp { get; set; }
        public bool Stato_Record_Tab_Check_Imp { get; set; }
    }
}
