//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_GridLookup
    {
        public int Tab_GridLookup_Id { get; set; }
        public bool Campo_Db { get; set; }
        public int Campo_Filtro { get; set; }
        public bool Campo_Localizzato { get; set; }
        public bool Campo_NotOnlyInList { get; set; }
        public bool Campo_Selezionato { get; set; }
        public bool Campo_Video { get; set; }
        public bool Campo_Report { get; set; }
        public string NomeCampo { get; set; }
        public string NomeRicerca { get; set; }
        public string Nome_Risorsa { get; set; }
        public string NomeTab { get; set; }
        public string NomeTab_Decod { get; set; }
        public int Ordinamento { get; set; }
        public Nullable<int> Utenti_Id { get; set; }
        public string Width { get; set; }
        public bool IsInteger { get; set; }
        public string DefaultFilterExpression { get; set; }
    
        public virtual Utenti Utenti { get; set; }
    }
}
