//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Chk_Imp
    {
        public int Tab_Chk_Imp_Id { get; set; }
        public string Nome_Tabella_Tab_Check_Imp { get; set; }
        public string Chiave_Record_Tab_Check_Imp { get; set; }
        public bool Stato_Record_Tab_Check_Imp { get; set; }
    }
}
