//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Funz
    {
        public Tab_Funz()
        {
            this.Menu = new HashSet<Menu>();
            this.Tab_Aut = new HashSet<Tab_Aut>();
        }
    
        public int Tab_Funz_Id { get; set; }
        public int Dflt_Grid_Edit_Mode { get; set; }
        public string Link_Tab_Funz { get; set; }
        public string Nome_Tab_Funz { get; set; }
        public int Dflt_OnOffBtnVisible { get; set; }
    
        public virtual ICollection<Menu> Menu { get; set; }
        public virtual ICollection<Tab_Aut> Tab_Aut { get; set; }
    }
}
