//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_EditFormTemplate
    {
        public int Tab_EditFormTemplate_Id { get; set; }
        public string Entity_Tab_EditFormTemplate { get; set; }
        public string Tabs_Tab_EditFormTemplate { get; set; }
        public string Fields_Tab_EditFormTemplate { get; set; }
    }
}
