//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Comuni
    {
        public int Tab_Comuni_Id { get; set; }
        public string Cap_Tab_Comuni { get; set; }
        public string Luogo_Tab_Comuni { get; set; }
        public string Codice_Luogo_Tab_Comuni { get; set; }
        public int Codice_Istat_Tab_Comuni { get; set; }
        public int Tab_Prov_Id { get; set; }
        public string Codice_Prov_Tab_Comuni { get; set; }
    
        public virtual Tab_Prov Tab_Prov { get; set; }
    }
}
