//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Decod
    {
        public Tab_Decod()
        {
            this.Tab_Dist = new HashSet<Tab_Dist>();
            this.Regs = new HashSet<Reg>();
            this.Damage = new HashSet<Damage>();
            this.Tab_Damage = new HashSet<Tab_Damage>();
        }
    
        public int Tab_Decod_Id { get; set; }
        public string Gruppo_Tab { get; set; }
        public string Nome_Tab { get; set; }
        public string Chiave_Tab { get; set; }
        public string Decodifica_Tab { get; set; }
        public string Campo1_Tab { get; set; }
    
        public virtual ICollection<Tab_Dist> Tab_Dist { get; set; }
        public virtual ICollection<Reg> Regs { get; set; }
        public virtual ICollection<Damage> Damage { get; set; }
        public virtual ICollection<Tab_Damage> Tab_Damage { get; set; }
    }
}
