//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Dist
    {
        public int Tab_Dist_Id { get; set; }
        public string Arrivo_Tab_Dist { get; set; }
        public decimal KM_Tab_Dist { get; set; }
        public int Minuti_Tab_Dist { get; set; }
        public string Partenza_Tab_Dist { get; set; }
        public int Tab_Decod_Id { get; set; }
    
        public virtual Tab_Decod Tab_Decod { get; set; }
    }
}
