//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Messaggi
    {
        public int Tab_Messaggi_Id { get; set; }
        public int Applicazione_Tab_Messaggi_Id { get; set; }
        public System.DateTime Data_Tab_Messaggi { get; set; }
        public string Testo_Tab_Messaggi { get; set; }
        public int Funzione_Tab_Messaggi_Id { get; set; }
        public Nullable<System.DateTime> Data_Ora_Elab_Tab_Messaggi { get; set; }
        public Nullable<int> Utente_Id { get; set; }
    
        public virtual Utenti Utenti { get; set; }
    }
}
