//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timesheet
    {
        public int TimesheetId { get; set; }
        public int ColId { get; set; }
        public System.DateTime Month { get; set; }
        public string Justification { get; set; }
        public Nullable<System.TimeSpan> Day01 { get; set; }
        public Nullable<System.TimeSpan> Day02 { get; set; }
        public Nullable<System.TimeSpan> Day03 { get; set; }
        public Nullable<System.TimeSpan> Day04 { get; set; }
        public Nullable<System.TimeSpan> Day05 { get; set; }
        public Nullable<System.TimeSpan> Day06 { get; set; }
        public Nullable<System.TimeSpan> Day07 { get; set; }
        public Nullable<System.TimeSpan> Day08 { get; set; }
        public Nullable<System.TimeSpan> Day09 { get; set; }
        public Nullable<System.TimeSpan> Day10 { get; set; }
        public Nullable<System.TimeSpan> Day11 { get; set; }
        public Nullable<System.TimeSpan> Day12 { get; set; }
        public Nullable<System.TimeSpan> Day13 { get; set; }
        public Nullable<System.TimeSpan> Day14 { get; set; }
        public Nullable<System.TimeSpan> Day15 { get; set; }
        public Nullable<System.TimeSpan> Day16 { get; set; }
        public Nullable<System.TimeSpan> Day17 { get; set; }
        public Nullable<System.TimeSpan> Day18 { get; set; }
        public Nullable<System.TimeSpan> Day19 { get; set; }
        public Nullable<System.TimeSpan> Day20 { get; set; }
        public Nullable<System.TimeSpan> Day21 { get; set; }
        public Nullable<System.TimeSpan> Day22 { get; set; }
        public Nullable<System.TimeSpan> Day23 { get; set; }
        public Nullable<System.TimeSpan> Day24 { get; set; }
        public Nullable<System.TimeSpan> Day25 { get; set; }
        public Nullable<System.TimeSpan> Day26 { get; set; }
        public Nullable<System.TimeSpan> Day27 { get; set; }
        public Nullable<System.TimeSpan> Day28 { get; set; }
        public Nullable<System.TimeSpan> Day29 { get; set; }
        public Nullable<System.TimeSpan> Day30 { get; set; }
        public Nullable<System.TimeSpan> Day31 { get; set; }
        public Nullable<int> CantId { get; set; }
    
        public virtual Col Col { get; set; }
    }
}
