//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utenti
    {
        public Utenti()
        {
            this.Cant_Note = new HashSet<Cant_Note>();
            this.Col_Note = new HashSet<Col_Note>();
            this.Menu_Tipo = new HashSet<Menu_Tipo>();
            this.Tab_Aut = new HashSet<Tab_Aut>();
            this.Tab_DataGrid = new HashSet<Tab_DataGrid>();
            this.Tab_GridLookup = new HashSet<Tab_GridLookup>();
            this.Tab_Messaggi = new HashSet<Tab_Messaggi>();
            this.Tab_Report = new HashSet<Tab_Report>();
            this.Utenti_Fil = new HashSet<Utenti_Fil>();
            this.Utenti_History = new HashSet<Utenti_History>();
            this.Utenti_Resp = new HashSet<Utenti_Resp>();
        }
    
        public int Utenti_Id { get; set; }
        public string Codice_Utente { get; set; }
        public System.DateTime Data_Registrazione_Utente { get; set; }
        public System.DateTime DataOraUltimaModifica_Utente { get; set; }
        public bool Disabilitazione_Utente { get; set; }
        public bool Fil_Inclusive { get; set; }
        public int Lingue_Id { get; set; }
        public Nullable<int> Versioni_Id { get; set; }
        public int Menu_Tipo_Id { get; set; }
        public string Note_Utente { get; set; }
        public string PasswordHash_Utente { get; set; }
        public bool Resp_Inclusive { get; set; }
        public string SaltKey_Utente { get; set; }
        public Nullable<int> Col_Id { get; set; }
        public Nullable<int> Cli_Id { get; set; }
        public Nullable<int> N_GG_Val_Psw_Utente { get; set; }
        public Nullable<System.DateTime> DataUltimoAgg_Psw_Utente { get; set; }
        public string SecretQuestion { get; set; }
        public string SecretAnswer { get; set; }
        public bool AllowSupervisedLogin { get; set; }
        public bool ChangePasswordOnLogin { get; set; }
        public int ChangePasswordWarningDays { get; set; }
    
        public virtual ICollection<Cant_Note> Cant_Note { get; set; }
        public virtual Cli Cli { get; set; }
        public virtual Col Col { get; set; }
        public virtual ICollection<Col_Note> Col_Note { get; set; }
        public virtual Lingue Lingue { get; set; }
        public virtual ICollection<Menu_Tipo> Menu_Tipo { get; set; }
        public virtual Menu_Tipo Menu_Tipo1 { get; set; }
        public virtual ICollection<Tab_Aut> Tab_Aut { get; set; }
        public virtual ICollection<Tab_DataGrid> Tab_DataGrid { get; set; }
        public virtual ICollection<Tab_GridLookup> Tab_GridLookup { get; set; }
        public virtual ICollection<Tab_Messaggi> Tab_Messaggi { get; set; }
        public virtual ICollection<Tab_Report> Tab_Report { get; set; }
        public virtual ICollection<Utenti_Fil> Utenti_Fil { get; set; }
        public virtual ICollection<Utenti_History> Utenti_History { get; set; }
        public virtual ICollection<Utenti_Resp> Utenti_Resp { get; set; }
        public virtual Versioni Versioni { get; set; }
    }
}
