//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utenti_History
    {
        public int Utenti_History_Id { get; set; }
        public int Utenti_Id { get; set; }
        public System.DateTime Data_Change_Psw_Utenti_History { get; set; }
        public System.DateTime Data_Old_Change_Psw_Utenti_History { get; set; }
        public string Password_Hash_Utenti_History { get; set; }
        public string Salt_Key_Utenti_History { get; set; }
    
        public virtual Utenti Utenti { get; set; }
    }
}
