//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utenti_Fil
    {
        public int Utenti_Fil_Id { get; set; }
        public int Fil_Id { get; set; }
        public int Utenti_Id { get; set; }
        public int Dominio_Utenti_Fil { get; set; }
    
        public virtual Fil Fil { get; set; }
        public virtual Utenti Utenti { get; set; }
    }
}
