//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utenti_Resp
    {
        public int Utenti_Resp_Id { get; set; }
        public int Resp_Id { get; set; }
        public int Utenti_Id { get; set; }
        public int Dominio_Utenti_Resp { get; set; }
    
        public virtual Resp Resp { get; set; }
        public virtual Utenti Utenti { get; set; }
    }
}
