//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utenti_History
    {
        public int Utenti_History_Id { get; set; }
        public int Utenti_Id { get; set; }
        public System.DateTime Data_Change_Psw_Utenti_History { get; set; }
        public System.DateTime Data_Old_Change_Psw_Utenti_History { get; set; }
        public string Password_Hash_Utenti_History { get; set; }
        public string Salt_Key_Utenti_History { get; set; }
    
        public virtual Utenti Utenti { get; set; }
    }
}
