//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Versioni
    {
        public Versioni()
        {
            this.Resources = new HashSet<Resources>();
            this.Utenti = new HashSet<Utenti>();
        }
    
        public int Versioni_Id { get; set; }
        public System.DateTime Data_Registrazione_Versioni { get; set; }
        public System.DateTime DataOraUltimaModifica_Versioni { get; set; }
        public bool DisAbilitazione_Versioni { get; set; }
        public string Nome_Versioni { get; set; }
    
        public virtual ICollection<Resources> Resources { get; set; }
        public virtual ICollection<Utenti> Utenti { get; set; }
    }
}
