//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|\\MDBSchema\\Power_Tabe" +
            "lle.mdb;Persist Security Info=True")]
        public string Power_TabelleConnectionString {
            get {
                return ((string)(this["Power_TabelleConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|\\MDBSchema\\PowerMDBSc" +
            "hema.mdb;Persist Security Info=True")]
        public string PowerMDBSchemaConnectionString {
            get {
                return ((string)(this["PowerMDBSchemaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=\"|DataDirectory|\\MDBSchema\\Power_Tab" +
            "elle MOSAICO 2012-06-22 ALLEGERITO.mdb\";Persist Security Info=True")]
        public string Power_Tabelle_MOSAICO_2012_06_22_ALLEGERITOConnectionString {
            get {
                return ((string)(this["Power_Tabelle_MOSAICO_2012_06_22_ALLEGERITOConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=\"D:\\Stefano\\Sviluppo\\Power\\Power_Tab" +
            "elle MOSAICO 2012-06-22 ALLEGERITO.mdb\"")]
        public string Power_Tabelle_MOSAICO_2012_06_22_ALLEGERITOConnectionString1 {
            get {
                return ((string)(this["Power_Tabelle_MOSAICO_2012_06_22_ALLEGERITOConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=\"|DataDirectory|\\MDBSchema\\Power_Tab" +
            "elle MOSAICO 2012-06-22 PER POWER WEB.mdb\";Persist Security Info=True")]
        public string Power_Tabelle_MOSAICO_2012_06_22_PER_POWER_WEBConnectionString {
            get {
                return ((string)(this["Power_Tabelle_MOSAICO_2012_06_22_PER_POWER_WEBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|\\MDBSchema\\PowerMDB.m" +
            "db;Persist Security Info=True")]
        public string PowerMDBConnectionString {
            get {
                return ((string)(this["PowerMDBConnectionString"]));
            }
        }
    }
}
