//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using log4net;
    using Domain;
    
    public partial class PowerWebEntities : DbContext
    {
       private ILog _log = LogManager.GetLogger(typeof(PowerWebEntities));
    
       public ILog Log { get { return _log; } }
    
        public PowerWebEntities()
            : this("name=PowerWebEntities")
        {
        }
    
    	 public PowerWebEntities(String connectionString)
            : base(connectionString)
        {
            //this.SavingChanges += PowerWebEntities_SavingChanges;
            this.Database.Log = s => System.Diagnostics.Debug.WriteLine(s);
    	}
    
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cli> Cli { get; set; }
        public DbSet<Col_Monte_Minuti> Col_Monte_Minuti { get; set; }
        public DbSet<Fil> Fil { get; set; }
        public DbSet<Fru> Fru { get; set; }
        public DbSet<Fru_Cant> Fru_Cant { get; set; }
        public DbSet<Lingue> Lingue { get; set; }
        public DbSet<Menu> Menu { get; set; }
        public DbSet<Pru> Pru { get; set; }
        public DbSet<Pru_Col> Pru_Col { get; set; }
        public DbSet<Resources> Resources { get; set; }
        public DbSet<Resp> Resp { get; set; }
        public DbSet<Tab_Aut> Tab_Aut { get; set; }
        public DbSet<Tab_Cap> Tab_Cap { get; set; }
        public DbSet<Tab_Chk_Imp> Tab_Chk_Imp { get; set; }
        public DbSet<Tab_Comuni> Tab_Comuni { get; set; }
        public DbSet<Tab_DataGrid> Tab_DataGrid { get; set; }
        public DbSet<Tab_Decod> Tab_Decod { get; set; }
        public DbSet<Tab_EditFormTemplate> Tab_EditFormTemplate { get; set; }
        public DbSet<Tab_Festivi> Tab_Festivi { get; set; }
        public DbSet<Tab_Messaggi> Tab_Messaggi { get; set; }
        public DbSet<Tab_Orari> Tab_Orari { get; set; }
        public DbSet<Tab_Orari_Tipo> Tab_Orari_Tipo { get; set; }
        public DbSet<Tab_Prov> Tab_Prov { get; set; }
        public DbSet<Tab_Report> Tab_Report { get; set; }
        public DbSet<Tab_Report_Group> Tab_Report_Group { get; set; }
        public DbSet<Tab_Report_Order> Tab_Report_Order { get; set; }
        public DbSet<Utenti_Fil> Utenti_Fil { get; set; }
        public DbSet<Utenti_Resp> Utenti_Resp { get; set; }
        public DbSet<Versioni> Versioni { get; set; }
        public DbSet<Cant_Fil_V> Cant_Fil_V { get; set; }
        public DbSet<Col_Resp_V> Col_Resp_V { get; set; }
        public DbSet<MetaDescriptor> MetaDescriptor { get; set; }
        public DbSet<MetaFieldDescriptor> MetaFieldDescriptor { get; set; }
        public DbSet<Cant_Note> Cant_Note { get; set; }
        public DbSet<Col_Note> Col_Note { get; set; }
        public DbSet<Utenti> Utenti { get; set; }
        public DbSet<Tab_GridLookup> Tab_GridLookup { get; set; }
        public DbSet<Col_V> Col_V { get; set; }
        public DbSet<PendingElab> PendingElab { get; set; }
        public DbSet<Menu_Tipo> Menu_Tipo { get; set; }
        public DbSet<Cant_Var> Cant_Var { get; set; }
        public DbSet<Tab_Funz> Tab_Funz { get; set; }
        public DbSet<Tab_Dist> Tab_Dist { get; set; }
        public DbSet<Col_Var> Col_Var { get; set; }
        public DbSet<Cant_V> Cant_V { get; set; }
        public DbSet<Col_Cant_Orario> Col_Cant_Orario { get; set; }
        public DbSet<Reg_Stored> Reg_Stored { get; set; }
        public DbSet<Timesheet> Timesheets { get; set; }
        public DbSet<Col> Col { get; set; }
        public DbSet<Reg> Regs { get; set; }
        public DbSet<Tab_Excel_Model> Tab_Excel_Model { get; set; }
        public DbSet<Aut_Str> Aut_Str { get; set; }
        public DbSet<Reg_V> Reg_V { get; set; }
        public DbSet<Param> Param { get; set; }
        public DbSet<Utenti_History> Utenti_History { get; set; }
        public DbSet<Cant> Cant { get; set; }
        public DbSet<Damage> Damage { get; set; }
        public DbSet<Tab_Damage> Tab_Damage { get; set; }
    
        public virtual int Reg_Delete(string xML)
        {
            var xMLParameter = xML != null ?
                new ObjectParameter("XML", xML) :
                new ObjectParameter("XML", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Reg_Delete", xMLParameter);
        }
    
        public virtual int Reg_Insert(string xML)
        {
            var xMLParameter = xML != null ?
                new ObjectParameter("XML", xML) :
                new ObjectParameter("XML", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Reg_Insert", xMLParameter);
        }
    
        public virtual int Reg_Update(string xML)
        {
            var xMLParameter = xML != null ?
                new ObjectParameter("XML", xML) :
                new ObjectParameter("XML", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Reg_Update", xMLParameter);
        }
    
        public virtual int Archive(Nullable<System.DateTime> from, Nullable<System.DateTime> to)
        {
            var fromParameter = from.HasValue ?
                new ObjectParameter("From", from) :
                new ObjectParameter("From", typeof(System.DateTime));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("To", to) :
                new ObjectParameter("To", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Archive", fromParameter, toParameter);
        }
    
        public virtual int Restore(Nullable<System.DateTime> from, Nullable<System.DateTime> to)
        {
            var fromParameter = from.HasValue ?
                new ObjectParameter("From", from) :
                new ObjectParameter("From", typeof(System.DateTime));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("To", to) :
                new ObjectParameter("To", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Restore", fromParameter, toParameter);
        }
    
    // void PowerWebEntities_SavingChanges(object sender, EventArgs e)
    //{
    //    StringBuilder sb = new StringBuilder();
    //    foreach (ObjectStateEntry objectStateEntry in
    //        this.ObjectStateManager.GetObjectStateEntries(EntityState.Added | EntityState.Deleted | EntityState.Modified))
    //    {
    //        sb.Append(objectStateEntry.State).Append(" ").Append(objectStateEntry.EntitySet.Name).Append(" by ").Append(PowerWebContext.Current.User.Codice_Utente).Append(Environment.NewLine);
    //
    //        if (Settings.Default.IsSaveChangesLogActive)
    //        {
    //
    //            if (objectStateEntry.State == EntityState.Added)
    //            {
    //                sb.Append("\t");
    //                for (int i = 0; i < objectStateEntry.CurrentValues.FieldCount; i++)
    //                {
    //                    if (!objectStateEntry.CurrentValues.IsDBNull(i))
    //                    {
    //                        object currentValue = objectStateEntry.CurrentValues.GetValue(i);
    //                        sb.Append(objectStateEntry.CurrentValues.GetName(i)).Append(":").Append(currentValue);
    //                        sb.Append("$");
    //                    }
    //                }
    //            }
    //            else if (objectStateEntry.State == EntityState.Deleted)
    //            {
    //                sb.Append("\t");
    //                for (int i = 0; i < objectStateEntry.OriginalValues.FieldCount; i++)
    //                {
    //                    if (!objectStateEntry.OriginalValues.IsDBNull(i))
    //                    {
    //                        object originalValue = objectStateEntry.OriginalValues.GetValue(i);
    //                        sb.Append(objectStateEntry.OriginalValues.GetName(i)).Append(":").Append(originalValue);
    //                        sb.Append("$");
    //                    }
    //                }
    //            }
    //            else if (objectStateEntry.State == EntityState.Modified)
    //            {
    //                sb.Append("\t");
    //                foreach (string item in objectStateEntry.GetModifiedProperties())
    //                {
    //                    object originalValue = objectStateEntry.OriginalValues[item];
    //                    sb.Append(item).Append(":").Append(originalValue);
    //
    //                    if (objectStateEntry.State == EntityState.Modified)
    //                    {
    //                        object currentValue = objectStateEntry.CurrentValues[item];
    //
    //                        if (!originalValue.Equals(currentValue))
    //                            sb.Append("->").Append(currentValue);
    //                    }
    //
    //                    sb.Append("$");
    //                }
    //            }
    //
    //            sb.Append(Environment.NewLine);
    //
    //        }
    //    }
    //    _log.Info(sb.ToString());
    //}
    
    }
    
    
    
    
}
