//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Domain;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PowerWebEntities : DbContext
    {
        public PowerWebEntities(string connectionString)
            : base(connectionString)
        {

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aut_Str> Aut_Str { get; set; }
        public virtual DbSet<Cant_Note> Cant_Note { get; set; }
        public virtual DbSet<Cant_Var> Cant_Var { get; set; }
        public virtual DbSet<Cli> Cli { get; set; }
        public virtual DbSet<Col> Col { get; set; }
        public virtual DbSet<Col_Cant_Orario> Col_Cant_Orario { get; set; }
        public virtual DbSet<Col_Monte_Minuti> Col_Monte_Minuti { get; set; }
        public virtual DbSet<Col_Note> Col_Note { get; set; }
        public virtual DbSet<Col_Var> Col_Var { get; set; }
        public virtual DbSet<Damage> Damage { get; set; }
        public virtual DbSet<Fil> Fil { get; set; }
        public virtual DbSet<Fru> Fru { get; set; }
        public virtual DbSet<Fru_Cant> Fru_Cant { get; set; }
        public virtual DbSet<Lingue> Lingue { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Menu_Tipo> Menu_Tipo { get; set; }
        public virtual DbSet<MetaDescriptor> MetaDescriptor { get; set; }
        public virtual DbSet<MetaFieldDescriptor> MetaFieldDescriptor { get; set; }
        public virtual DbSet<PendingElab> PendingElab { get; set; }
        public virtual DbSet<Pru> Pru { get; set; }
        public virtual DbSet<Pru_Col> Pru_Col { get; set; }
        public virtual DbSet<Reg> Reg { get; set; }
        public virtual DbSet<Reg_Stored> Reg_Stored { get; set; }
        public virtual DbSet<Resources> Resources { get; set; }
        public virtual DbSet<Resp> Resp { get; set; }
        public virtual DbSet<Tab_Aut> Tab_Aut { get; set; }
        public virtual DbSet<Tab_Cap> Tab_Cap { get; set; }
        public virtual DbSet<Tab_Chk_Imp> Tab_Chk_Imp { get; set; }
        public virtual DbSet<Tab_Comuni> Tab_Comuni { get; set; }
        public virtual DbSet<Tab_Damage> Tab_Damage { get; set; }
        public virtual DbSet<Tab_DataGrid> Tab_DataGrid { get; set; }
        public virtual DbSet<Tab_Decod> Tab_Decod { get; set; }
        public virtual DbSet<Tab_Dist> Tab_Dist { get; set; }
        public virtual DbSet<Tab_EditFormTemplate> Tab_EditFormTemplate { get; set; }
        public virtual DbSet<Tab_Excel_Model> Tab_Excel_Model { get; set; }
        public virtual DbSet<Tab_Festivi> Tab_Festivi { get; set; }
        public virtual DbSet<Tab_Funz> Tab_Funz { get; set; }
        public virtual DbSet<Tab_GridLookup> Tab_GridLookup { get; set; }
        public virtual DbSet<Tab_Messaggi> Tab_Messaggi { get; set; }
        public virtual DbSet<Tab_Orari> Tab_Orari { get; set; }
        public virtual DbSet<Tab_Orari_Tipo> Tab_Orari_Tipo { get; set; }
        public virtual DbSet<Tab_Prov> Tab_Prov { get; set; }
        public virtual DbSet<Tab_Report> Tab_Report { get; set; }
        public virtual DbSet<Tab_Report_Group> Tab_Report_Group { get; set; }
        public virtual DbSet<Tab_Report_Order> Tab_Report_Order { get; set; }
        public virtual DbSet<Timesheet> Timesheet { get; set; }
        public virtual DbSet<Utenti> Utenti { get; set; }
        public virtual DbSet<Utenti_Fil> Utenti_Fil { get; set; }
        public virtual DbSet<Utenti_History> Utenti_History { get; set; }
        public virtual DbSet<Utenti_Resp> Utenti_Resp { get; set; }
        public virtual DbSet<Versioni> Versioni { get; set; }
        public virtual DbSet<Cant_Fil_V> Cant_Fil_V { get; set; }
        public virtual DbSet<Cant_V> Cant_V { get; set; }
        public virtual DbSet<Col_Resp_V> Col_Resp_V { get; set; }
        public virtual DbSet<Col_V> Col_V { get; set; }
        public virtual DbSet<CentroDiCosto> CentroDiCosto { get; set; }
        public virtual DbSet<Cant_CentroDiCosto> Cant_CentroDiCosto { get; set; }
        public virtual DbSet<Cant> Cant { get; set; }
        public virtual DbSet<Param> Param { get; set; }
        public virtual DbSet<Reg_V> Reg_V { get; set; }
    
        public virtual int Archive(Nullable<System.DateTime> from, Nullable<System.DateTime> to)
        {
            var fromParameter = from.HasValue ?
                new ObjectParameter("From", from) :
                new ObjectParameter("From", typeof(System.DateTime));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("To", to) :
                new ObjectParameter("To", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Archive", fromParameter, toParameter);
        }
    
        public virtual int Reg_Delete(string xML)
        {
            var xMLParameter = xML != null ?
                new ObjectParameter("XML", xML) :
                new ObjectParameter("XML", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Reg_Delete", xMLParameter);
        }
    
        public virtual int Reg_Insert(string xML)
        {
            var xMLParameter = xML != null ?
                new ObjectParameter("XML", xML) :
                new ObjectParameter("XML", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Reg_Insert", xMLParameter);
        }
    
        public virtual int Reg_Update(string xML)
        {
            var xMLParameter = xML != null ?
                new ObjectParameter("XML", xML) :
                new ObjectParameter("XML", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Reg_Update", xMLParameter);
        }
    
        public virtual int Restore(Nullable<System.DateTime> from, Nullable<System.DateTime> to)
        {
            var fromParameter = from.HasValue ?
                new ObjectParameter("From", from) :
                new ObjectParameter("From", typeof(System.DateTime));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("To", to) :
                new ObjectParameter("To", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Restore", fromParameter, toParameter);
        }
    }
}
