//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da uno strumento.
//
//     Le modifiche a questo file possono causare un comportamento non corretto e verranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerWeb.Account
{


  public partial class ChangePassword
  {

    /// <summary>
    /// Controllo ChangeUserPassword.
    /// </summary>
    /// <remarks>
    /// Campo generato automaticamente.
    /// Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    /// </remarks>
    protected global::System.Web.UI.WebControls.ChangePassword ChangeUserPassword;
  }
}
